### ISSUE TITLE
Diagnose speed trouble in diag.F

### ISSUE THREAD

**Issue by smchen2020** [DOI-USGS/COAWST#10]
The diagnosing function to indicate where the speed trouble is in COAWST-modified ROMS (diag.F) is awesome. However, it uses uv_max=max(u, v) that the extra-large magnitude of negative velocities will be ignored. The abs() is necessary for this max-comparison.

Cheers,
Shi-ming Chen

**Comment by jcwarner-usgs** [comment]
added.
