### ISSUE TITLE
COAWST V3.6 Compiling error

### ISSUE THREAD

**Issue by moeraj** [DOI-USGS/COAWST#11]
I've been compiling COAWST model and creating a WRF-ROMS-SWAN coupled model. It seems that there is some problem with creating executable file coawstM (including SANDY and customized case), I can compiled successfully WRF and ROMS  separately.
how can fix it , if it's a problem with the unfitted compiler options? thanks a lot !

Here is my error message:
`/public1/soft/intel/2018/compilers_and_libraries_2018.2.199/linux/mpi/intel64/bin/mpiifort -fp-model precise -ip -O3 -traceback -check uninit -assume byterecl -I/public3/home/sc52807/BKY/COAWST/MCT2/include -I/public3/home/sc52807/BKY/COAWST-master//WRF/main -I/public3/home/sc52807/BKY/COAWST-master//WRF/external/esmf_time_f90 -I/public3/home/sc52807/BKY/COAWST-master//WRF/frame -I/public3/home/sc52807/BKY/COAWST-master//WRF/share -fp-model precise -ip -O3 -traceback -check uninit ./Build/roms_import.o ./Build/get_sparse_matrix.o ./Build/master.o ./Build/roms_export.o ./Build/read_coawst_par.o ./Build/get_wrf_moving_grids.o ./Build/get_numswan_grids.o ./Build/mct_coupler_utils.o ./Build/mct_coupler_params.o ./Build/propagator.o ./Build/read_model_inputs.o ./Build/ocean_coupler.o ./Build/coupler.o ./Build/mod_coupler_iounits.o ./Build/mod_coupler_kinds.o ./Build/esmf_roms.o ./Build/ocean_control.o ./Build/ww3_iounits.o -o coawstM ./Build/libNLM.a ./Build/libNLM_bio.a ./Build/libNLM_sed.a ./Build/libNLM_wec.a ./Build/libNLM_veg.a ./Build/libANA.a ./Build/libUTIL.a ./Build/libMODS.a ./Build/libSWAN.a ./Build/libNLM.a -L/public3/home/sc52807/BKY/app/files/needed/lib -lnetcdf -L/public3/home/sc52807/BKY/app/files/needed/lib -lnetcdf -lnetcdff /public3/home/sc52807/BKY/COAWST-master/Build/mct_coupler_params.o -L/public3/home/sc52807/BKY/COAWST/MCT2/lib -lmct -lmpeu WRF/main/module_wrf_top.o WRF/main/libwrflib.a WRF/external/fftpack/fftpack5/libfftpack.a WRF/external/io_grib1/libio_grib1.a WRF/external/io_grib_share/libio_grib_share.a WRF/external/io_int/libwrfio_int.a WRF/external/esmf_time_f90/libesmf_time.a WRF/external/RSL_LITE/librsl_lite.a WRF/frame/module_internal_header_util.o WRF/frame/pack_utils.o WRF/external/io_netcdf/libwrfio_nf.a
/public3/home/sc52807/BKY/COAWST-master/Build/mct_coupler_params.o: In function `mct_coupler_params._':mct_coupler_params.f90:(.text+0x0): multiple definition of `mct_coupler_params._'
/public3/home/sc52807/BKY/COAWST-master/Build/mct_coupler_params.o: In function `mct_coupler_params_mp_allocate_coupler_params_':
mct_coupler_params.f90:(.text+0x10): multiple definition of `mct_coupler_params_mp_allocate_coupler_params_'
./Build/mct_coupler_params.o:mct_coupler_params.f90:(.text+0x10): first defined here
/public3/home/sc52807/BKY/COAWST-master/Build/mct_coupler_params.o:(.bss+0x600): multiple definition of `mct_coupler_params_mp_nocn2wav_'
./Build/mct_coupler_params.o:(.bss+0x600): first defined here
/public3/home/sc52807/BKY/COAWST-master/Build/mct_coupler_params.o:(.bss+0x5a0): multiple definition of `mct_coupler_params_mp_nwav2ocn_'
./Build/mct_coupler_params.o:(.bss+0x5a0): first defined here
/public3/home/sc52807/BKY/COAWST-master/Build/mct_coupler_params.o:(.bss+0x540): multiple definition of `mct_coupler_params_mp_nocnfwav_'
./Build/mct_coupler_params.o:(.bss+0x540): first defined here
/public3/home/sc52807/BKY/COAWST-master/Build/mct_coupler_params.o:(.bss+0x4e0): multiple definition of `mct_coupler_params_mp_nwavfocn_'
./Build/mct_coupler_params.o:(.bss+0x4e0): first defined here
/public3/home/sc52807/BKY/COAWST-master/Build/mct_coupler_params.o:(.bss+0x480): multiple definition of `mct_coupler_params_mp_nocn2atm_'
./Build/mct_coupler_params.o:(.bss+0x480): first defined here
/public3/home/sc52807/BKY/COAWST-master/Build/mct_coupler_params.o:(.bss+0x420): multiple definition of `mct_coupler_params_mp_natm2ocn_'
./Build/mct_coupler_params.o:(.bss+0x420): first defined here
/public3/home/sc52807/BKY/COAWST-master/Build/mct_coupler_params.o:(.bss+0x3c0): multiple definition of `mct_coupler_params_mp_nocnfatm_'
./Build/mct_coupler_params.o:(.bss+0x3c0): first defined here
/public3/home/sc52807/BKY/COAWST-master/Build/mct_coupler_params.o:(.bss+0x360): multiple definition of `mct_coupler_params_mp_natmfocn_'
······`

**Comment by jcwarner-usgs** [comment]
can you post (or attach) the whole build?  that actual error may have happened a lot earlier in the build.

**Comment by moeraj** [comment]
I have solve this problem by annotated code related USE_SCRIPT in Compilers/Linux-***.mk（line217-219）：
#ifndef USE_SCRIP
#             LIBS += $(MCT_PARAMS_DIR)/mct_coupler_params.o
#endif

I don't know if it is because of using ifndef , somehow it was fixed.

**Comment by moeraj** [comment]
I have solve this problem by annotated code related _USE_SCRIPT_ in Compilers/Linux-***.mk（line217-219）：
#ifndef USE_SCRIP
#     LIBS += $(MCT_PARAMS_DIR)/mct_coupler_params.o
#endif

I don't know if it is because of using _ifndef_ , somehow it was fixed.

**Comment by moeraj** [comment]
I have solve this problem by annotated code related USE_SCRIPT in Compilers/Linux-***.mk（line217-219）：
#ifndef USE_SCRIP
#LIBS += $(MCT_PARAMS_DIR)/mct_coupler_params.o
#endif

I don't know if it is because of using ifndef , somehow it was fixed.
