### ISSUE TITLE
COAWST V3.6 Compiling error

### ISSUE THREAD

**Issue by ben108472** [DOI-USGS/COAWST#12]
EL/COAWST//WRF/share bc_4d.f90
cd ./Build; /opt/openmpi-1.10.1-intel2016-ib/bin/mpif90 -c -fp-model precise -ip -O3 -traceback -check uninit -assume byterecl -I/Dellwork5/cwuben/MODEL/MCT/include -I/Dellwork5/cwuben/MODEL/COAWST//WRF/main -I/Dellwork5/cwuben/MODEL/COAWST//WRF/external/esmf_time_f90 -I/Dellwork5/cwuben/MODEL/COAWST//WRF/frame -I/Dellwork5/cwuben/MODEL/COAWST//WRF/share conv_2d.f90
cd ./Build; /opt/openmpi-1.10.1-intel2016-ib/bin/mpif90 -c -fp-model precise -ip -O3 -traceback -check uninit -assume byterecl -I/Dellwork5/cwuben/MODEL/MCT/include -I/Dellwork5/cwuben/MODEL/COAWST//WRF/main -I/Dellwork5/cwuben/MODEL/COAWST//WRF/external/esmf_time_f90 -I/Dellwork5/cwuben/MODEL/COAWST//WRF/frame -I/Dellwork5/cwuben/MODEL/COAWST//WRF/share -free mod_netcdf.f90
cd ./Build; /opt/openmpi-1.10.1-intel2016-ib/bin/mpif90 -c -fp-model precise -ip -O3 -traceback -check uninit -assume byterecl -I/Dellwork5/cwuben/MODEL/MCT/include -I/Dellwork5/cwuben/MODEL/COAWST//WRF/main -I/Dellwork5/cwuben/MODEL/COAWST//WRF/external/esmf_time_f90 -I/Dellwork5/cwuben/MODEL/COAWST//WRF/frame -I/Dellwork5/cwuben/MODEL/COAWST//WRF/share -free stats.f90
cd ./Build; /opt/openmpi-1.10.1-intel2016-ib/bin/mpif90 -c -fp-model precise -ip -O3 -traceback -check uninit -assume byterecl -I/Dellwork5/cwuben/MODEL/MCT/include -I/Dellwork5/cwuben/MODEL/COAWST//WRF/main -I/Dellwork5/cwuben/MODEL/COAWST//WRF/external/esmf_time_f90 -I/Dellwork5/cwuben/MODEL/COAWST//WRF/frame -I/Dellwork5/cwuben/MODEL/COAWST//WRF/share vegetation_drag.f90
cd ./Build; /opt/openmpi-1.10.1-intel2016-ib/bin/mpif90 -c -fp-model precise -ip -O3 -traceback -check uninit -assume byterecl -I/Dellwork5/cwuben/MODEL/MCT/include -I/Dellwork5/cwuben/MODEL/COAWST//WRF/main -I/Dellwork5/cwuben/MODEL/COAWST//WRF/external/esmf_time_f90 -I/Dellwork5/cwuben/MODEL/COAWST//WRF/frame -I/Dellwork5/cwuben/MODEL/COAWST//WRF/share gls_prestep.f90
cd ./Build; /opt/openmpi-1.10.1-intel2016-ib/bin/mpif90 -c -fp-model precise -ip -O3 -traceback -check uninit -assume byterecl -I/Dellwork5/cwuben/MODEL/MCT/include -I/Dellwork5/cwuben/MODEL/COAWST//WRF/main -I/Dellwork5/cwuben/MODEL/COAWST//WRF/external/esmf_time_f90 -I/Dellwork5/cwuben/MODEL/COAWST//WRF/frame -I/Dellwork5/cwuben/MODEL/COAWST//WRF/share ice_frazil.f90
cd ./Build; /opt/openmpi-1.10.1-intel2016-ib/bin/mpif90 -c -fp-model precise -ip -O3 -traceback -check uninit -assume byterecl -I/Dellwork5/cwuben/MODEL/MCT/include -I/Dellwork5/cwuben/MODEL/COAWST//WRF/main -I/Dellwork5/cwuben/MODEL/COAWST//WRF/external/esmf_time_f90 -I/Dellwork5/cwuben/MODEL/COAWST//WRF/frame -I/Dellwork5/cwuben/MODEL/COAWST//WRF/share u2dbc_im.f90
cd ./Build; /opt/openmpi-1.10.1-intel2016-ib/bin/mpif90 -c -fp-model precise -ip -O3 -traceback -check uninit -assume byterecl -I/Dellwork5/cwuben/MODEL/MCT/include -I/Dellwork5/cwuben/MODEL/COAWST//WRF/main -I/Dellwork5/cwuben/MODEL/COAWST//WRF/external/esmf_time_f90 -I/Dellwork5/cwuben/MODEL/COAWST//WRF/frame -I/Dellwork5/cwuben/MODEL/COAWST//WRF/share v2dbc_im.f90
cd ./Build; /opt/openmpi-1.10.1-intel2016-ib/bin/mpif90 -c -fp-model precise -ip -O3 -traceback -check uninit -assume byterecl -I/Dellwork5/cwuben/MODEL/MCT/include -I/Dellwork5/cwuben/MODEL/COAWST//WRF/main -I/Dellwork5/cwuben/MODEL/COAWST//WRF/external/esmf_time_f90 -I/Dellwork5/cwuben/MODEL/COAWST//WRF/frame -I/Dellwork5/cwuben/MODEL/COAWST//WRF/share mod_fourdvar.f90
cd ./Build; /opt/openmpi-1.10.1-intel2016-ib/bin/mpif90 -c -fp-model precise -ip -O3 -traceback -check uninit -assume byterecl -I/Dellwork5/cwuben/MODEL/MCT/include -I/Dellwork5/cwuben/MODEL/COAWST//WRF/main -I/Dellwork5/cwuben/MODEL/COAWST//WRF/external/esmf_time_f90 -I/Dellwork5/cwuben/MODEL/COAWST//WRF/frame -I/Dellwork5/cwuben/MODEL/COAWST//WRF/share ocean_coupler.f90
cd ./Build; /opt/openmpi-1.10.1-intel2016-ib/bin/mpif90 -c -fp-model precise -ip -O3 -traceback -check uninit -assume byterecl -I/Dellwork5/cwuben/MODEL/MCT/include -I/Dellwork5/cwuben/MODEL/COAWST//WRF/main -I/Dellwork5/cwuben/MODEL/COAWST//WRF/external/esmf_time_f90 -I/Dellwork5/cwuben/MODEL/COAWST//WRF/frame -I/Dellwork5/cwuben/MODEL/COAWST//WRF/share lmd_bkpp.f90
cd ./Build; /opt/openmpi-1.10.1-intel2016-ib/bin/mpif90 -c -fp-model precise -ip -O3 -traceback -check uninit -assume byterecl -I/Dellwork5/cwuben/MODEL/MCT/include -I/Dellwork5/cwuben/MODEL/COAWST//WRF/main -I/Dellwork5/cwuben/MODEL/COAWST//WRF/external/esmf_time_f90 -I/Dellwork5/cwuben/MODEL/COAWST//WRF/frame -I/Dellwork5/cwuben/MODEL/COAWST//WRF/share lmd_skpp.f90
ocean_coupler.f90(832): error #6460: This is not a field name that is defined in the encompassing structure.   [RMASK_WET]
          IF (GRID(ng)%rmask_wet(i,j).lt.0.5_r8) THEN
-----------------------^
ocean_coupler.f90(832): error #6158: The structure-name is invalid or is missing.   [GRID]
          IF (GRID(ng)%rmask_wet(i,j).lt.0.5_r8) THEN
--------------^
compilation aborted for ocean_coupler.f90 (code 1)
make: *** [Build/ocean_coupler.o] Error 1
make: *** Waiting for unfinished jobs....

Here is the error message.

**Comment by jcwarner-usgs** [comment]
oops sorry.  i added a check to the swan coupling to make swan mask =0 when the cells were dry.  Please do an update (the file changed was Master/mct_roms_swan.h).  Then do a recompile and see if that fixed it.  please let me know if that worked.
thanks,
john

**Comment by ben108472** [comment]
This error is solved by your latest update.
But I still cannot successfully compile due to the lack of wrf.exe.
Here is the log file.

[build.log](https://github.com/jcwarner-usgs/COAWST/files/5185701/build.log)

**Comment by jcwarner-usgs** [comment]
if you do
ls -ltr
do you have a coawstM  ??? if so, then you are good.
if you create a coupled application, then you will not get a wrf.exe, you will not get a swan.exe, and you will not get a roms.exe.  You will only get one executable and that is coawstM.

-john



John C. Warner, Ph.D.
U.S. Geological Survey
384 Woods Hole Road
Woods Hole, MA 02543
508-457-2237<tel:508-457-2237> ph. 508-457-2310<tel:508-457-2310> fax
jcwarner@usgs.gov<mailto:jcwarner@usgs.gov>

https://www.usgs.gov/staff-profiles/john-warner


________________________________

**Comment by ben108472** [comment]
Thank you.
I have successfully run the job.
