### ISSUE TITLE
SWAN+WRF coupling problem using COAWST

### ISSUE THREAD

**Issue by mf99274** [DOI-USGS/COAWST#13]
Hi all,

In order to make the full coupling (WRF+SWAN+ROMS) I am taking baby steps and trying to see if the models are working properly by themselves and coupled. As of right now, I am trying to couple only SWAN+WRF to see if they would work before adding my ROMS model that is already working. When I define ROMS plus all the other flags, coawst.bash generates the binary file but when I undefine ROMS and just leave the commands below,

#undef ROMS_MODEL
#define SWAN_MODEL
#define WRF_MODEL
#define MCT_LIB
#define MCT_INTERP_WV2AT

coawst.bash gives the error below:

**roms_export.f90:16:10:**

       USE mod_kinds
          1
**Fatal Error: Can't open module file ‘mod_kinds.mod’ for reading at (1): No such file or directory
compilation terminated.
Master/Module.mk:28: recipe for target '/home/mfocean/coawst/Projects/southernCCS_swan+WRF/Build/roms_export.o' failed
make: *** [/home/mfocean/coawst/Projects/southernCCS_swan+WRF/Build/roms_export.o] Error 1
make: *** Waiting for unfinished jobs....**

which is weird since I am not defining ROMS and it's trying to export ROMS fields. So I was wondering if the coupling method will only work when ROMS is defined either with SWAN or WRF, and therefore, I could make ROMS boundaries closed or maybe I am leaving something out that I should add in order to this coupling to work.

Thank you in advance,
Matheus

**update:**

I have used the latest version found here and the error still persists.

**Comment by jcwarner-usgs** [comment]
ok. so i just downloaded a new version and compiled it. I had a problem, but it was in get_sparse_matrix. I fixed that, and pushed that to the svn and github sites. After my sparse fix, i was able to get a coawstM.  I did not get your error.
So please try this:  get a new version. i am not sure how you are updating, but make sure the file
Master/roms_export.F has

#include "cppdefs.h"
      MODULE ROMS_export_mod
#ifdef ROMS_COUPLING
...

that is the most recent version.
-j

**Comment by mf99274** [comment]
Hi John, 

Thank you for looking into it. I re-downloaded COAWST again and it works now (maybe I had an old coawst.zip file in my folder and ended up unzip that). 

Thank you,
