### ISSUE TITLE
Some questions about the SST in the WRF+ROMS coupled model

### ISSUE THREAD

**Issue by nuist2284494698** [DOI-USGS/COAWST#16]
Hi, Jcwarner

I am a postgraduate student of  NUIST and doing some researches on oceanic eddies with this coupled model. In my researches, I activated the ROMS and WRF, and the model run successfully. 
However, I met a problem when I tried to change the coupled SST that to be exported to the WRF model? Explicitly, I want to spatially smooth the coupled SST at the coupling timestep, and then use this smoothed SST to drive the WRF model. How can I achieve this goal?
In my previous attempt, I tried to open the CPP options 'SST_CONST' and close 'MCT_INTERP_OC2AT'. While the model run successfully, but as you know this configuration just a one-way couple. The SST is still read from the wrflow* file.

Thanks in advance and looking forward to your reply.

**Comment by jcwarner-usgs** [comment]
Good to hear from you.
The SST_CONST actually sets the SST to be a constant value, i think it is 25, and that is all WRF sees. It is an option mostly for testing, and not really what you want.
I am not sure how good of a coder you are, but to do some spatial averaging you would need to edit Master/mct_roms_wrf.h and from lines 681 to 689 there is code like:
      ij=0
      DO j=JstrR,JendR
        DO i=IstrR,IendR
          ij=ij+1
          A(ij)=OCEAN(ng)%t(i,j,N(ng),nstp(ng),itemp)
        END DO
      END DO

you would need to do the averaging in here, something like
      ij=0
      DO j=JstrR,JendR
        DO i=IstrR,IendR
          ij=ij+1
          A(ij)=0.2_r8*(OCEAN(ng)%t(i,j,N(ng),nstp(ng),itemp)+          &
     &                  OCEAN(ng)%t(i-1,j,N(ng),nstp(ng),itemp)+        &
     &                  OCEAN(ng)%t(i+1,j,N(ng),nstp(ng),itemp)+        &
     &                  OCEAN(ng)%t(i,j-1,N(ng),nstp(ng),itemp)+        &
     &                  OCEAN(ng)%t(i,j+1,N(ng),nstp(ng),itemp))
        END DO
      END DO

There might be an issue at the ROMS grid boundaries, but give this (or something similar) a try.
-j



John C. Warner, Ph.D.

U.S. Geological Survey
384 Woods Hole Road
Woods Hole, MA 02543
508-457-2237<tel:508-457-2237> ph. 508-457-2310<tel:508-457-2310> fax
jcwarner@usgs.gov<mailto:jcwarner@usgs.gov>

https://www.usgs.gov/staff-profiles/john-warner


________________________________

**Comment by nuist2284494698** [comment]
HI, John. I'm so glad and excited to have your help. I used  COAWST V3.4 in my research. But I still have curiosity in your guidance,
(1) In the code direction 'WRF/'frame/atm_couple.F' line 1903-1917, you can see the  SST_CONST option. I think this cpp option use the SST source just from the wrflow* file, isn't it?  
(2) Changes in the  Master/mct_roms_wrf.h' as you mentioned above, whether it can smooth the whole grid%sst in the WRF model?

**Comment by jcwarner-usgs** [comment]
-for the wrf/frame/atm_coupler.F 1903-1917
i see what you mean. The Amask will be 0, and then if just does
          cff=(AA(ij)+273.15)*Amask(ij)
          grid%sst(i,j)=cff+grid%sst(i,j)*(1.0-Amask(ij))
which is just
          grid%sst(i,j)=0 + grid%sst(i,j)
I thought at some point it kept the SST at 25, but maybe that was an older version.  any case we dont really use that option.

-changes to mct_roms_wrf.h would only change the SST from roms, not the entire SST in WRF.
If you want to smooth the entire SST to WRF, then you could edit the wrflow file, read that SST, smooth it in matlab, then write it back to that file.  Would that work?
-j


John C. Warner, Ph.D.
U.S. Geological Survey
384 Woods Hole Road
Woods Hole, MA 02543
508-457-2237<tel:508-457-2237> ph. 508-457-2310<tel:508-457-2310> fax
jcwarner@usgs.gov<mailto:jcwarner@usgs.gov>

https://www.usgs.gov/staff-profiles/john-warner


________________________________

**Comment by nuist2284494698** [comment]
Hi, John. I am so sorry for the delay in replying to you. And in my recent attempts, I have found an effective method to smooth the coupled grid%sst (transferred to the WRF) inline. That is,  do some modifications on the 'WRF/phys/module_surfave_driver.F', and the 'WRF/dyn_em/module_first_rk_step_part1.F'. Specifically, in the 'module_surface_driver.F' line 1490 the if (sst_update .eq. 1) block, we can use the variable XTIME, XLAT, XLONG and the coupling time interval to determine whether and how to smooth the grid%sst.

**Comment by jcwarner-usgs** [comment]
i think i see what you are doing. But i am not sure that smoothing the SST in that location is the best choice. You are in a tile, and if you need information outside that tile to make the average, then it may not be available.  This might cause some tiling bugs: ie you might see lines on the SST field.  It all depends on how you are doing this, but i would suggest you do the smoothing back in ROMS before the SST is sent to WRF. That way if you need a 5 point stencil or whatever size, it can be made available in roms to compute the averages.

**Comment by nuist2284494698** [comment]
Thanks a lot for your advice, John.  And I am going to  do more tests  and improvements on your first suggestion. By the way,  how can I  achieve your second suggstion roughly in the model codes, whether it is the guidance that you gave me previously: do modifications in the 'Master/mct_roms_wrf.h'

**Comment by jcwarner-usgs** [comment]
i provided some guidance above.  if you look on the github site, you can see this whole thread.
