### ISSUE TITLE
COAWST V3.6 Compiling error (about WRF libwrflib.a(module_io_quilt.o))

### ISSUE THREAD

**Issue by tofei-liu** [DOI-USGS/COAWST#18]
Hi, jcwarner, 

I have installed COAWST model (also MCT and SCRIP) followed “COAWST_User_Manual” and compiled  successfully WRF,  ROMS, and SWAN separately. However, there are several problems when I compiled a WRF-ROMS-SWAN coupled model to simulate Hurricane Sandy, details are described in the attach files (coawst.bash, sandy.h and build.log). 

COAWST source code was downloaded from https://github.com/jcwarner-usgs/COAWST.git directly via Git on November 22.
Compiler: Inter 15.0.1 with netcdf-4.4.1, mpich-3.1.

The exact errors in build.log is as follows(from line5222 to the end) :
_WRF/frame/module_internal_header_util.o WRF/frame/pack_utils.o WRF/external/io_netcdf/libwrfio_nf.a
WRF/main/**libwrflib.a(module_io_quilt.o)**: In function `module_wrf_quilt_mp_quilt_': 
module_io_quilt.f90:(.text+0x962d): **undefined reference to** `ext_pnc_inquire_filename_'
module_io_quilt.f90:(.text+0x965b): undefined reference to `ext_pnc_ioclose_'
WRF/main/libwrflib.a(module_io.o): In function `module_io_mp_wrf_get_dom_ti_real_arr_':
module_io.f90:(.text+0x30d): undefined reference to `ext_pnc_get_dom_ti_real_'
WRF/main/libwrflib.a(module_io.o): In function `module_io_mp_wrf_get_dom_ti_real_sca_':
......
WRF/main/libwrflib.a(module_io.o): In function `wrf_read_field1_':
module_io.f90:(.text+0x1f811): undefined reference to `ext_pnc_read_field_'
WRF/main/libwrflib.a(module_io.o): In function `wrf_write_field1_':
module_io.f90:(.text+0x20c04): undefined reference to `ext_pnc_write_field_'
make: *** [/WORK/sio_goc25/COAWST_3.6/COAWST/Projects/My_Project/Sandylf/coawstM] Error 1_

Looking forward to your reply and thanks for your help!
Fu Liu

[coawst.bash.txt](https://github.com/jcwarner-usgs/COAWST/files/5724582/coawst.bash.txt)
[sandylf.h.txt](https://github.com/jcwarner-usgs/COAWST/files/5724583/sandylf.h.txt)
[Sandy_coupled_build3.log](https://github.com/jcwarner-usgs/COAWST/files/5724584/Sandy_coupled_build3.log)

**Comment by jcwarner-usgs** [comment]
had to think on this one.
i think these calls "ext_pnc_read"  etc
are for parallel netcdf I/O.  Are you trying to use that?  Can you compile without parallel io netcdf.
i see you have
Will use NETCDF in dir: /WORK/app/netcdf/4.4.1/00-CF-15-par
Will use PNETCDF in dir: /WORK/app/pnetcdf/1.6.1/00-icc15

is the -par mean parallel? can you compile with a non-parallel netcdf library?

**Comment by tofei-liu** [comment]
Hi, jcwarner,

Thanks for your great suggestion!

You’re right, the ‘-par’ means parallel.
The problem was solved by removing the PNETCDF. 
The coupled model was compiled successfully without PNETCDF while the version of NETCDF was not changed.

Thanks again for your fast reply and have a nice day!

Fu Liu

**Comment by jcwarner-usgs** [comment]
good to hear!
