### ISSUE TITLE
When USE_DEBUG=on, then an error occurred during compiling

### ISSUE THREAD

**Issue by yuke4500** [DOI-USGS/COAWST#19]
Hi, jcwarner
I can compile  COAWST-3.5 (WRF-ROMS) successfully and get "coawstM" when I annotate the line "USE_DEBUG=on" in coawst.bash. But when I want to turn on this option, I cant compile the model. It says that the problems are in the file read_coawst_par.f90 like 
cd ./Build; /opt/intel/intel2017u8/compilers_and_libraries_2017.8.262/linux/mpi/intel64/bin/mpiifort -c -fp-model precise -g -check all -check bounds -traceback -check uninit -warn interfaces,nouncalled -gen-interfaces -g -check bounds -check uninit -traceback -warn interfaces,nouncalled -gen-interfaces -ftrapuv -fpe0 -I/home/keyu/libs/MCT/MCT-2.6.0-intel2017/include -I/home/keyu/work/models/CPL/COAWST-3.5-bsiso-test2-debug/WRF/main -I/home/keyu/work/models/CPL/COAWST-3.5-bsiso-test2-debug/WRF/external/esmf_time_f90 -I/home/keyu/work/models/CPL/COAWST-3.5-bsiso-test2-debug/WRF/frame -I/home/keyu/work/models/CPL/COAWST-3.5-bsiso-test2-debug/WRF/share read_coawst_par.f90
read_coawst_par.f90(90): error #8284: If the actual argument is scalar, the dummy argument shall be scalar unless the actual argument is of type character or is an element of an array that is not assumed shape, pointer, or polymorphic.   [VOUT]
              Npts=cload_i(Nval, Rval, 1, NnodesATM)
-------------------^
read_coawst_par.f90(92): error #8284: If the actual argument is scalar, the dummy argument shall be scalar unless the actual argument is of type character or is an element of an array that is not assumed shape, pointer, or polymorphic.   [VOUT]
              Npts=cload_i(Nval, Rval, 1, NnodesWAV)
-------------------^
read_coawst_par.f90(94): error #8284: If the actual argument is scalar, the dummy argument shall be scalar unless the actual argument is of type character or is an element of an array that is not assumed shape, pointer, or polymorphic.   [VOUT]
              Npts=cload_i(Nval, Rval, 1, NnodesOCN)
-------------------^
read_coawst_par.f90(96): error #8284: If the actual argument is scalar, the dummy argument shall be scalar unless the actual argument is of type character or is an element of an array that is not assumed shape, pointer, or polymorphic.   [VOUT]
              Npts=cload_r(Nval, Rval, 1, TI_ATM2WAV)
-------------------^
read_coawst_par.f90(98): error #8284: If the actual argument is scalar, the dummy argument shall be scalar unless the actual argument is of type character or is an element of an array that is not assumed shape, pointer, or polymorphic.   [VOUT]
              Npts=cload_r(Nval, Rval, 1, TI_ATM2OCN)
-------------------^
read_coawst_par.f90(100): error #8284: If the actual argument is scalar, the dummy argument shall be scalar unless the actual argument is of type character or is an element of an array that is not assumed shape, pointer, or polymorphic.   [VOUT]
              Npts=cload_r(Nval, Rval, 1, TI_WAV2ATM)
-------------------^
read_coawst_par.f90(102): error #8284: If the actual argument is scalar, the dummy argument shall be scalar unless the actual argument is of type character or is an element of an array that is not assumed shape, pointer, or polymorphic.   [VOUT]
              Npts=cload_r(Nval, Rval, 1, TI_WAV2OCN)
-------------------^
read_coawst_par.f90(104): error #8284: If the actual argument is scalar, the dummy argument shall be scalar unless the actual argument is of type character or is an element of an array that is not assumed shape, pointer, or polymorphic.   [VOUT]
              Npts=cload_r(Nval, Rval, 1, TI_OCN2WAV)
-------------------^
read_coawst_par.f90(106): error #8284: If the actual argument is scalar, the dummy argument shall be scalar unless the actual argument is of type character or is an element of an array that is not assumed shape, pointer, or polymorphic.   [VOUT]
              Npts=cload_r(Nval, Rval, 1, TI_OCN2ATM)
-------------------^
read_coawst_par.f90(119): error #8284: If the actual argument is scalar, the dummy argument shall be scalar unless the actual argument is of type character or is an element of an array that is not assumed shape, pointer, or polymorphic.   [VOUT]
              Npts=cload_i(Nval, Rval, 1, scrip_opt)
-------------------^
compilation aborted for read_coawst_par.f90 (code 1)
make: *** [Build/read_coawst_par.o] Error 1

And I attatched my build.log file and coawst.bash, too. Looking forward to your reply and thank you very much!
Ke Yu
[coawst.bash -build-log.zip](https://github.com/jcwarner-usgs/COAWST/files/5744641/coawst.bash.-build-log.zip)

The reason that I want to recompile COAWST is that when I ran COAWST, I met errors like:
forrtl: severe (174): SIGSEGV, segmentation fault occurred
Image              PC                Routine            Line        Source
coawstM            000000000363E1F4  Unknown               Unknown  Unknown
libpthread-2.17.s  00002AC500AAC630  Unknown               Unknown  Unknown
libc-2.17.so       00002AC500D3EAEC  cfree                 Unknown  Unknown
coawstM            0000000003685D38  Unknown               Unknown  Unknown
coawstM            0000000000864B8C  Unknown               Unknown  Unknown
coawstM            00000000008DE501  Unknown               Unknown  Unknown
coawstM            00000000008D5BE6  Unknown               Unknown  Unknown
coawstM            0000000000414835  MAIN__                    217  master.f90
coawstM            0000000000412B9E  Unknown               Unknown  Unknown
libc-2.17.so       00002AC500CDB555  __libc_start_main     Unknown  Unknown
coawstM            0000000000412AA9  Unknown               Unknown  Unknown

The only thing I know is in the master.f90 (217):
!-----------------------------------------------------------------------
!  Run coupled models according to the processor rank.
!-----------------------------------------------------------------------
!
      IF (MyColor.eq.ATMcolor) THEN
        CALL wrf_init (MyCOMM)                ----------------217
        CALL wrf_run
        CALL wrf_finalize(.TRUE.)
      END IF
      IF (MyColor.eq.OCNcolor) THEN
        first=.TRUE.
        Nrun=1
        IF (exit_flag.eq.NoError) THEN
          CALL ROMS_initialize (first, MyCOMM)
        END IF
        IF (exit_flag.eq.NoError) THEN
          run_time=0.0_m8
          DO ng=1,Ngrids
            run_time=MAX(run_time, dt(ng)*ntimes(ng))
          END DO
          CALL ROMS_run (run_time)
        END IF
        CALL ROMS_finalize
        CALL finalize_ocn2atm_coupling
      END IF
!
!-----------------------------------------------------------------------
So I indeed need 'USE_DEBUG=on'
Here is my log-file for the crashed running and the corresponding ocean*.in and coupling*.in files.
Seems that "ATMgrid 01 dt= * -to- OCNgrid 01 dt= *, CplInt:* Steps: *" is not generated and the model crashed at this step.
Is this problem related with the compiling problem when USE_DEBUG=on? (NnodesATM...) 

[coupling_bsiso.in.txt](https://github.com/jcwarner-usgs/COAWST/files/5744855/coupling_bsiso.in.txt)
[ocean_new_bsiso.in.txt](https://github.com/jcwarner-usgs/COAWST/files/5744856/ocean_new_bsiso.in.txt)
[run.log1.txt](https://github.com/jcwarner-usgs/COAWST/files/5744857/run.log1.txt)

**Comment by jcwarner-usgs** [comment]
i have had this problem compiling with debug before.  and i could not find the reason, guess i did  not spend enough time on it.   Suggest we find a different way to figure out your issue because it looks like the problem is in WRF, not ROMS.  so debug=on only compiles roms with debug, and this will most likely not really help in this case.

-I see in the run log there is
"Max map factor in domain 1 =  1.28. Scale the dt in the model accordingly."
for the coupling, we can not let WRF adjust the dt.  because the models need to step on a dt interval that will allow all the models to reach a common time level.  if wrf uses some strange dt, then it will most likely never exactly reach the synchronization point.  so can you make it so wrf does not use a modified dt?

-maybe it is because you are using this conus configuration, and so the code is not set up to read those input files?? what does your wrf input look like?

-I also see
"W A R N I N G : Problem opening my_iofields_list.txt
 Ignoring problems reading my_iofields_list.txt
Continuing.  To make this a fatal error, set ignore_iofields_warn to false in namelist"
do you know how to fix this?

Have you tried to run WRF by itself in this setup???
-j

**Comment by yuke4500** [comment]
Thanks for you suggestion. I ran WRF in this setup smoothly. Sorry for forgetting to put my_iofields_list.txt in the working direction if the warning is misleading.
Here is my namelist.input and rsl.out.0000
[namelist.input.txt](https://github.com/jcwarner-usgs/COAWST/files/5749325/namelist.input.txt)
[rsl.out.0000.txt](https://github.com/jcwarner-usgs/COAWST/files/5749326/rsl.out.0000.txt)
I also got 'Max map factor in domain 1 =  1.28. Scale the dt in the model accordingly.' in rsl.out.0000 and this did not affect the running.

Then I tried COAWST without CONUS configuration, the same error occurred.
[run.log2.txt](https://github.com/jcwarner-usgs/COAWST/files/5749398/run.log2.txt)
Maybe the problem is not in WRF.

[error-in-shell.txt](https://github.com/jcwarner-usgs/COAWST/files/5749399/error-in-shell.txt) This error information is the same with that when running with CONUS.
What does 'Error in `./coawstM': corrupted size vs. prev_size' mean? 

Ke Yu

**Comment by jcwarner-usgs** [comment]
ok, try this for starters:

edit your namelist.input and make max dom have a comma at the end
 max_dom                             = 1,

i think the comma is needed to get the end of line flag.
-j

**Comment by yuke4500** [comment]
Thanks for your help! My experiment is running smoothly now.

Ke Yu

**Comment by jcwarner-usgs** [comment]
Nice!
