### ISSUE TITLE
wrf error when running JOE_TC DiffGrid

### ISSUE THREAD

**Issue by Jaleen-Z** [DOI-USGS/COAWST#21]
Hi:

I have successfully compiled the joe_tc diffgrid case in COAWST. But when I'm running it gives the following error:
d01 2014-07-19_00:00:00  Input data is acceptable to use: wrflowinp_d01
d01 2014-07-19_00:00:00  Input data is acceptable to use:
d01 2014-07-19_00:00:00  Input data is acceptable to use:
d01 2014-07-19_00:00:00  Input data is acceptable to use:
d01 2014-07-19_00:00:00 Input data processed for aux input   4 for domain   1
open_aux_u : error opening auxinput5_d01_2014-07-19_00:00:00 for reading. 100
d01 2014-07-19_00:00:00 Input data processed for aux input   5 for domain   1
d01 2014-07-19_00:00:00 Input data processed for aux input   4 for domain   1
open_aux_u : error opening auxinput5_d01_2014-07-19_00:00:00 for reading. 100
d01 2014-07-19_00:00:00 Input data processed for aux input   5 for domain   1
d01 2014-07-19_00:00:00 Input data processed for aux input   4 for domain   1
open_aux_u : error opening auxinput5_d01_2014-07-19_00:00:00 for reading. 100
d01 2014-07-19_00:00:00 Input data processed for aux input   5 for domain   1
d01 2014-07-19_00:00:00 Input data processed for aux input   4 for domain   1
open_aux_u : error opening auxinput5_d01_2014-07-19_00:00:00 for reading. 100
d01 2014-07-19_00:00:00 Input data processed for aux input   5 for domain   1
Could anyone give some suggestions in solving this problem?

[err.txt](https://github.com/jcwarner-usgs/COAWST/files/5834929/err.txt)
[JOE_TCtest.out.txt](https://github.com/jcwarner-usgs/COAWST/files/5834931/JOE_TCtest.out.txt)
[namelist.input.txt](https://github.com/jcwarner-usgs/COAWST/files/5834932/namelist.input.txt)
[namelist.wps.txt](https://github.com/jcwarner-usgs/COAWST/files/5835002/namelist.wps.txt)

**Comment by jcwarner-usgs** [comment]
sorry for the long delay.
Are you trying to run WRF-CHEM? I have never tried that. not sure how that module works within WRF.
can you try it without the CHEM?

**Comment by Jaleen-Z** [comment]
Thanks for your great suggestion!
I will try it without the CHEM.
