### ISSUE TITLE
Coupled WRF-SWAN: segment number difference error

### ISSUE THREAD

**Issue by hillsmWNI** [DOI-USGS/COAWST#22]
Hi,

I have been having issues when trying to include a nested SWAN grid in a coupled WRF-SWAN run.

During initialisation of a run, the following error occurs and the code stops (just after starting 
on the second SWAN grid):

**MCT::m_SparseMatrixDecompComputeSegments_: segment number difference error, stat =1
000.MCT(MPEU)::die.: from MCT::m_SparseMatrixDecompComputeSegments_()
Abort(2) on node 0 (rank 0 in comm 0): application called MPI_Abort(MPI_COMM_WORLD, 2) - process 0**

I have been able to run the test simulations including a SWAN nest, and runs with a single SWAN grid are fine, so I presume this is related to the grids that I have built (either SWAN of the scrip file). Is there any available information about what might cause this error, or what the model is working on when it looks at this function?

I have checked through items such as grid size specification in the SWAN/SCRIP files, and they are all as required.

Thanks for any help,
Matt

[slurm-239.txt](https://github.com/jcwarner-usgs/COAWST/files/6016849/slurm-239.txt)

**Comment by jcwarner-usgs** [comment]
what are the swan and wrf grid sizes, and what did you have in the scrip.in?
looks like 2 wrf and 2 swan grids.
-j

**Comment by hillsmWNI** [comment]
Hi John,

Thanks for the quick reply.

Yes, 2 WRF and 2 SWAN grids.

WRF sizes are 120x115 and 229x211. SWAN sizes (size(h)) are 83x71 and 98x71. I have experimented with different sizes for the nested swan grid, but get the same result. Running with one SWAN grid works fine.

scrip.in contains:
OUTPUT_NCFILE='scrip_northsea.nc'

NGRIDS_SWAN=2,
NGRIDS_WRF=2,

SWAN_COORD(1)='/shared/exec/hillsm/COAWST/TESTS/North_Sea_WRF_SWAN/SWAN_GRID_VERSIONS/SWAN_9km/northsea_swan_coord.grd',
SWAN_COORD(2)='/shared/exec/hillsm/COAWST/TESTS/North_Sea_WRF_SWAN/SWAN_GRID_VERSIONS/SWAN_9km/northsea_swan_coord_ref3.grd',
SWAN_BATH(1)='/shared/exec/hillsm/COAWST/TESTS/North_Sea_WRF_SWAN/SWAN_GRID_VERSIONS/SWAN_9km/northsea_swan_bathy.bot',
SWAN_BATH(2)='/shared/exec/hillsm/COAWST/TESTS/North_Sea_WRF_SWAN/SWAN_GRID_VERSIONS/SWAN_9km/northsea_swan_bathy_ref3.bot',
SWAN_NUMX(1)=83,
SWAN_NUMX(2)=98,
SWAN_NUMY(1)=71,
SWAN_NUMY(2)=71,
CARTESIAN(1)=0,
CARTESIAN(2)=0,

WRF_GRIDS(1)='/shared/exec/hillsm/COAWST/TESTS/North_Sea_WRF_SWAN/wrfinput_d01',
WRF_GRIDS(2)='/shared/exec/hillsm/COAWST/TESTS/North_Sea_WRF_SWAN/wrfinput_d02',

The full output file is attached.

Thanks again,
Matt
[slurm-259.txt](https://github.com/jcwarner-usgs/COAWST/files/6017880/slurm-259.txt)

**Comment by jcwarner-usgs** [comment]
were you able to create the SCRIP file with just the wrf and swan grids, or are you using the scrip file generated with wrf+ roms+swan?

**Comment by hillsmWNI** [comment]
I had been having issues running SCRIP without ROMS turned on, so I was using a file with all weights for all three models.

I saw you updated read_swan.f, which fixed scrip so it runs with ROMS=0 (thanks).

I tried the updated version by still get the same crash.

Are there any requirements of the tiling for SWAN in terms ratios or sizes of the parent and nested grids?

**SWAN grid   2 is preparing computation

MCT::m_MCTWorld::initm_MCTERROR:  MCTWorld has already been initialized...Continuing

MCT::m_SparseMatrixDecompComputeSegments_: segment number difference error, stat =1
000.MCT(MPEU)::die.: from MCT::m_SparseMatrixDecompComputeSegments_()
Abort(2) on node 0 (rank 0 in comm 0): application called MPI_Abort(MPI_COMM_WORLD, 2)**

**Comment by jcwarner-usgs** [comment]
yes there are limitations for SWAN tiling. SWAN tiles only in 1 direction - the longer direction. for you it would be the x-direction for both swan grids.  you want each tile to have some wet points. it might not like if one tile is all dry or all land masked.

if you used 18 cores for the wave, then 98/18 ~ 4 cells width for each tile strip.  that might be too small?? just give it a try with like 4 cores to swan, just to see if that is the issue.

Are there any Err* files?  what do the PRINT files say?

**Comment by jcwarner-usgs** [comment]
going through these tickets and checking on this status.  are you making progress?

**Comment by thushiyang** [comment]
I also met this issue,  with Swan's nested grids on multiple occasions. Usually, I would comment out some of the Swan's nested grid functions, and then it would be possible to run the program. Perhaps it's wcap or quad.
