### ISSUE TITLE
Compile error of COAWST/WRF using gcc10

### ISSUE THREAD

**Issue by LemingVan** [DOI-USGS/COAWST#23]
I installed pkgs with Homebrew following [here](https://www.myroms.org/forum/viewtopic.php?t=3716).

I got errors when compiled the JOE_TC/Coupled test case, and I'm pretty sure it's related to WRF model.

Here is what I have done.
(1)compiling the COAWST/WRF (Version: 4.1.5) alone. Failed.

> ./clean -a
> ./configure [choose: 33 & 0]
>./compile em_squall2d_x >& wrfv4.1.5-1.log

I got these files (first one is configure.wrf file):
[configure.wrf-v4.1.5-1.log](https://github.com/jcwarner-usgs/COAWST/files/6017172/configure.wrf-v4.1.5-1.log)
[wrfv4.1.5-1.log](https://github.com/jcwarner-usgs/COAWST/files/6017171/wrfv4.1.5-1.log)

(2)compiling the WRF (Version: 4.2.2, from [here](https://github.com/wrf-model/WRF)) alone. Successful.

> ./clean -a
> ./configure [choose: 33 & 0]
>./compile em_squall2d_x >& wrfv4.2.2.log

I got these files:
[configure.wrf-v4.2.2.log](https://github.com/jcwarner-usgs/COAWST/files/6017175/configure.wrf-v4.2.2.log)
[wrfv4.2.2.log](https://github.com/jcwarner-usgs/COAWST/files/6017176/wrfv4.2.2.log)

(3)editing configure.wrf and compiling the COAWST/WRF (Version: 4.1.5)alone. Failed.
add these lines to configure.wrf:
> FCCOMPAT        =        -fallow-argument-mismatch -fallow-invalid-boz
> FCBASEOPTS_NO_G =       -w $(FORMAT_FREE) $(BYTESWAPIO) $(FCCOMPAT)

compile:
>./compile em_squall2d_x >& wrfv4.1.5-2.log

I got these files:
[configure.wrf-v4.1.5-2.log](https://github.com/jcwarner-usgs/COAWST/files/6017180/configure.wrf-v4.1.5-2.log)
[wrfv4.1.5-2.log](https://github.com/jcwarner-usgs/COAWST/files/6017181/wrfv4.1.5-2.log)

**Comment by LemingVan** [comment]
It seems like step (3) fixed some errors, but there are other ones.
I don't know how to solve the new problems in step (3).
Any suggestions?

**Comment by jcwarner-usgs** [comment]
Please look in the COAWST manual on how to compile the system The coawst system needs to control the build for each component, so we dont compile wrf that way. We compile all the components the same way.  You can follow the examples for the Sandy test case.  these are in Sections 5 for general description, Section 8 for WRF. 
basically you need to create a project.h file, use coawst.bash to build.  even if you only use 1 component, you use coawst.bash to build. 
take a look at the manual and see if that helps out.

**Comment by LemingVan** [comment]
Hi, @jcwarner-usgs 
When I compiled the Sandy test, I got the errors.
[coawst.log](https://github.com/jcwarner-usgs/COAWST/files/6019438/coawst.log)

I'd like to know, can I replace the COAWST/WRF(v4.1.5) with WRF(v4.2.2) myself? I think the errors come from the version of WRF.

What should I change/add in the new WRF(v4.2.2) in order to couple with other models?

**Comment by LemingVan** [comment]
<img width="1272" alt="屏幕快照 2021-02-22 下午1 29 35" src="https://user-images.githubusercontent.com/46369483/108666548-4d334980-7512-11eb-8449-c9e493b034c8.png">

**Comment by jcwarner-usgs** [comment]
Ok.  So I just downloaded a version of COAWST, set up the coawst.bash for the Sandy case, did a ./coawst.bash, selected 15 and 1 for WRF build, and it built fine.  So i can not recreate your issue.

I looked at your coawst.log for your sandy build, and i see things like:
"No rule to make target `/Users/leming/Documents/Models/COAWST-master/mct_coupler_params.o', needed by `atm_coupler.o'.  Stop."
So i think you might be using an older version of the coawst.bash, or makefile, or Compilers file.
Can you check that those files are consistent with the ones we distribute?

-johjn

**Comment by LemingVan** [comment]
I downloaded COAWST from https://codeload.github.com/jcwarner-usgs/COAWST/zip/master at February 18, 2021.
So I think they are consistent.
If possible, could you tell me the version of your gcc/gfortran?

**Comment by davegill** [comment]
@LemingVan @jcwarner-usgs 
Are you able to build WRF v4.1.5 stand-alone with GNU 10, if you add in the additional compilation flags?

```
git clone https://github.com/wrf-model/WRF WRF_test
cd WRF_test
git checkout release-v4.1.5
```

1. ADD IN THE REQUIRED COMPILATION FLAGS TO arch/configure.defaults (the `configure.wrf` is likely easier, after the `configure` step)
2. Make sure that you have the NETCDF env variable set and pointing to the correct location
3. Do a serial build, so there is no need for MPI

```
./configure -d
./compile em_real >& foo
```

Take a look at the executables:
```
ls -ls main/*.exe
```

**Comment by jcwarner-usgs** [comment]
when you built the sandy test case, what WRF options did you select?  i dont see how you set those?
you can do 
script build.log
./coawst.bash -j 4
[when done type exit]
then send that build.log

In your coawst.log i see "make[4]: Nothing to be done for `default'."
so that tells me you may not have set the correct options. 
then it goes directly to the netcdf build
"( cd /Users/leming/Documents/Models/COAWST-master/WRF/external/io_netcdf ; \"
So something is not being set correctly during the build.

-j

**Comment by LemingVan** [comment]
Hi @davegill 
Followed your guidance, I downloaded the WRF(v4.1.5) from [here](https://codeload.github.com/wrf-model/WRF/tar.gz/v4.1.5).
And added compilation flags to `arch/configure.defaults`, chose the 15 & 1, I can compile the `em_real` case successfully.

[configure.defaults.log](https://github.com/jcwarner-usgs/COAWST/files/6027150/configure.defaults.log)
[foo.log](https://github.com/jcwarner-usgs/COAWST/files/6027153/foo.log)

When I did the same to COAWST/WRF, compiled the WRF alone, I failed again.

**Comment by LemingVan** [comment]
Hi @jcwarner-usgs
I added compilation flags to `COAWST/WRF/arch/configure.defaults`, compiled the coawst.bash, chose the 15 & 1 for WRF, just did what you said.
But I still can't compile the Sandy case. Sorry to say that.
[build.log](https://github.com/jcwarner-usgs/COAWST/files/6027381/build.log)


The NETCDF path I have written to ~/.bash_profile.
> export NETCDF=/usr/local/opt/netcdf

**Comment by jcwarner-usgs** [comment]
ok we are actually getting somewhere.
when you compile coawst, you need to select an option with mpi (dmpar). for me it is 15, but it is different for you.

Please select from among the following Darwin ARCH options:

  1. (serial)   2. (smpar)   3. (dmpar)   4. (dm+sm)   PGI (pgf90/pgcc)
  5. (serial)   6. (smpar)   7. (dmpar)   8. (dm+sm)   INTEL (ifort/icc)
  9. (serial)  10. (smpar)  11. (dmpar)  12. (dm+sm)   INTEL (ifort/clang)
 13. (serial)               14. (dmpar)                GNU (g95/gcc)
 15. (serial)  16. (smpar)  17. (dmpar)  18. (dm+sm)   GNU (gfortran/gcc)
 19. (serial)  20. (smpar)  21. (dmpar)  22. (dm+sm)   GNU (gfortran/clang)
 23. (serial)               24. (dmpar)                IBM (xlf90_r/cc)
 25. (serial)  26. (smpar)  27. (dmpar)  28. (dm+sm)   PGI (pgf90/pgcc): -f90=pgf90
 29. (serial)  30. (smpar)  31. (dmpar)  32. (dm+sm)   INTEL (ifort/icc): Open MPI
 33. (serial)  34. (smpar)  35. (dmpar)  36. (dm+sm)   GNU (gfortran/gcc): Open MPI

looks like you use gfortran, so try 17

**Comment by LemingVan** [comment]
Bad luck, looks like the same errors.
Here is the build log.
[build.log](https://github.com/jcwarner-usgs/COAWST/files/6029849/build.log)
Maybe I should wait for the update of COAWST.

**Comment by jcwarner-usgs** [comment]
can you send the output from the WRF build that did work?  i guess you may have to rebuild that.
The problems in the build.log now are not really associated with coawst. For example it says

"/Users/leming/Documents/Models/COAWST-master/WRF/tools/standard.exe module_compute_geop.bb | /usr/bin/cpp -P -traditional -traditional-cpp > module_compute_geop.f90
sed -e "s/^\!.*'.*//" -e "s/^ *\!.*'.*//" module_check_a_mundo.F > module_check_a_mundo.G
sed: RE error: illegal byte sequence
make[3]: [module_check_a_mundo.o] Error 1 (ignored)"

so i would like to see how your correct build dealt with that.

**Comment by LemingVan** [comment]
Hi @jcwarner-usgs ,
I think I have made some progress.
I replaced the `main` and `share` folders of COAWST/WRF with Github/WRF(v4.1.5)'s, in this way, I can finally compile the `em_real case` successfully under the COAWST/WRF directory.

When I compiled with `./coawst.bash` (without nocleanwrf, try both 15.serial and 17.dmpar) under the COAWST directory, came back to the (same? maybe) errors again. See the [build.log](https://github.com/jcwarner-usgs/COAWST/files/6035976/build.log).

Which makes me confused is that, after compiling, WRF necessary executable files are generated, but it still failed in the end.
Do you know how to deal with it?

<img width="648" alt="屏幕快照 2021-02-24 下午8 43 45" src="https://user-images.githubusercontent.com/46369483/109002735-8bcb2e80-76e1-11eb-9d12-de3b1a1dcc79.png">

**Comment by jcwarner-usgs** [comment]
you can't just blindly replace contents of entire folders and expect it to work. By doing that you removed build flags in the wrf code that is associated with coawst.  the errors you have now are associated with the changes you made, so i can not support those changes.  they are not correct.

IF we go back to the original code distribution of COAWST, and try to build the Sandy case. The last time you tried this, the error was
sed -e "s/^\!.*'.*//" -e "s/^ *\!.*'.*//" module_check_a_mundo.F > module_check_a_mundo.G
sed: RE error: illegal byte sequence
I have no idea why that error occurred. It has nothing to do with COAWST. Maybe the multiple processor compilation caused a problem, not sure.

When you built the code most recently, that part of the code worked. It has nothing to do with my changes. 

So i am not sure why that sed command worked now but not before.
Can we try to recreate it?
Can you go back to the original COAWST distribution, try to compile Sandy with option 17.
-j

**Comment by LemingVan** [comment]
Sorry for the reckless approach to compile, because I have only learned `MITgcm`, and I am still new to `ROMS` and `WRF`. My understanding of `COAWST` is limited to the fact that it implements the exchange of data between different models through `MCT`, and I am not familiar with its specific implementation.
Therefore, I think that even under the `COAWST/WRF` directory, the `WRF` model can run alone without any problem.
Through my previous attempts, I found that the `main` and `share` folders (which may be limited to a single internal file change) are the obstacles that prevent the `WRF` model from running alone. This is of course my personal opinion and may not be entirely correct.

Okay, let's go back to the previous step (to avoid complicating the issue), I used the `COAWST` source code downloaded directly from `Github` and then changed the `COAWST/WRF/arch/configure.defaults` file to add `-fallow-argument-mismatch -fallow-invalid-boz` to the compilation flags, because gcc-10 will have problems compiling directly.
Then still use `./coawst.bash -j 4` to compile the Sandy case, selecting the `17` option, and below is the output file. This output file also contains the output of the `WRF` compilation, please note that it is before the "`Problems building executables, look for errors in the build log`".

[configure.defaults.log](https://github.com/jcwarner-usgs/COAWST/files/6040586/configure.defaults.log)
[configure.wrf.log](https://github.com/jcwarner-usgs/COAWST/files/6040587/configure.wrf.log)
[coawst.bash.log](https://github.com/jcwarner-usgs/COAWST/files/6040589/coawst.bash.log)
[build-new.log](https://github.com/jcwarner-usgs/COAWST/files/6040591/build-new.log)

<img width="652" alt="屏幕快照 2021-02-25 下午1 08 00" src="https://user-images.githubusercontent.com/46369483/109106529-ea88ba80-776a-11eb-8582-995f0ea14eb6.png">

**Comment by jcwarner-usgs** [comment]
ok. yes.  there are some things happening in your build that i do not understand.

lets try this.  I want you to get this file, rename it from module_check_a_mundo.F.log to module_check_a_mundo.F, place it in the folder WRF/share/ (it should replace the file in there),  and do a ./coawst.bash , 17, and see what happens. -j

[module_check_a_mundo.F.log](https://github.com/jcwarner-usgs/COAWST/files/6045389/module_check_a_mundo.F.log)

**Comment by davegill** [comment]
@jcwarner-usgs 
John,
I do not want to jump in the middle of this. I agree that the "illegal byte sequence" seems to probably be the real issue. That could happen when the source code is garbled. Also, with Mac, building source code is not really the best way to go, as they seem to be heading towards an IOS. Can we suggest trying the COAWST system on a larger computer than a laptop? Perhaps the more stable environment of a supported cluster would be an easier platform to attempt a build.

**Comment by LemingVan** [comment]
Hi @jcwarner-usgs ,

Here it is. 
[build.log](https://github.com/jcwarner-usgs/COAWST/files/6053755/build.log)

**Comment by LemingVan** [comment]
Followed @davegill's advice, using a different system (`Linux - ifort & mpich & netcdf4`), I can finally compile and run the Sandy case. Thanks for the help of @jcwarner-usgs and @davegill.
