### ISSUE TITLE
MCT::m_SparseMatrixPlus::initFromRoot_::

### ISSUE THREAD

**Issue by Ntmanh18196** [DOI-USGS/COAWST#25]
Hi John,
Following your suggestion, I post my issue in this site.
I got the problem which is related to the MCT:
> MCT::m_SparseMatrixPlus::initFromRoot_:: FATAL--length of vector y different from row count of sMat.Length of y = 111826 Number of rows in sMat = 111150
> 
My ROMS's domain has 390x285 grid points.
Besides, my SWAN's namelist likes that:
> 
PROJECT 'Haima' '1'
'3Way coupling WRF-SWAN-ROMS'
MODE NONSTATIONARY TWODIMENSIONAL
SET DEPMIN 0.10 INRHOG 1 NAUTICAL PWTAIL 5
COORDINATES SPHERICAL
&& KEYWORD for number of nested SWAN grids.
NSGRIDS 1
&& KEYWORDS TO CREATE AND READ COMPUTATIONAL GRID &&
CGRID CURVILINEAR 390 285 EXC 9.999000e+003 9.999000e+003 CIRCLE 36 0.04 1.0 24
READGRID COORDINATES 1 'Projects/Haima/swan_coord.grd' 4 0 0 FREE

&& KEYWORDS TO CREATE AND READ BATHYMETRY GRID &&
INPGRID BOTTOM CURVILINEAR 0 0 390 285 EXC 9.999000e+003
READINP BOTTOM 1 'Projects/Haima/swan_bathy.bot' 4 0 FREE

&& KEYWORD TO CREATE CURRENT GRID &&
INPGRID CURRENT CURVILINEAR 0 0 390 285 EXC 9.999000e+003 &
NONSTATIONARY 20161017.000000 6 DAY 20161022.000000

&& KEYWORD TO CREATE WATER LEVEL GRID &&
INPGRID WLEV CURVILINEAR 0 0 390 285 EXC 9.999000e+003 &
NONSTATIONARY 20161017.000000 6 DAY 20161023.000000

&& KEYWORD TO CREATE BOTTOM FRIC GRID &&
INPGRID FRIC CURVILINEAR 0 0 390 285 EXC 9.999000e+003 &
NONSTATIONARY 20161017.000000 6 DAY 20161023.000000
& Boundary files ****************************************
& 2D Spec Boundary files ****************************
BOUND SHAPESPEC JONSWAP MEAN DSPR DEGREES
BOUNDSPEC SEGMENT IJ 0 0 0 285 CONSTANT PAR 0.1 20.0 0.0 15
BOUNDSPEC SEGMENT IJ 0 0 390 0 CONSTANT PAR 0.1 20.0 0.0 15
BOUNDSPEC SEGMENT IJ 390 0 390 285 CONSTANT PAR 0.1 20.0 0.0 15
BOUNDSPEC SEGMENT IJ 0 285 390 285 CONSTANT PAR 0.1 20.0 0.0 15
& Restart name **********************************

&INIT
INIT_DEFAULT

& PHYSICS ****************************************
BREAKING CONSTANT 1.0 0.73
FRICTION MADSEN 0.05
&OFF QUAD
GEN3 KOMEN
WCAP KOM 2.36E-5 3.02E-3 2.0 1.0 1.0
PROP BSBT

BLOCK 'COMPGRID' NOHEADER 'Haima_hsig.mat' LAY 4 HSIGN 1. OUTPUT 20161017.000000 1 HR
BLOCK 'COMPGRID' NOHEADER 'Haima_xp.mat' LAY 4 XP 1.
BLOCK 'COMPGRID' NOHEADER 'Haima_yp.mat' LAY 4 YP 1.
BLOCK 'COMPGRID' NOHEADER 'Haima_wind.mat' LAY 4 WIND 1. OUTPUT 20161017.000000 1 HR
BLOCK 'COMPGRID' NOHEADER 'Haima_hsig.nc' LAY 4 HSIGN 1. OUTPUT 20161017.000000 1 HR
RESTART 'swan_rst.dat' FREE 1 HR

&COMPUTE STAT 20161017.000000
COMPUTE NONSTAT 20161017.000000 180 SEC 20161023.000000

HOTFILE 'Haima_init.hot'

STOP> 

And my sript.in is displayed in the below:
> SWAN_COORD(1)='../../Projects/Haima/swan_coord.grd',
SWAN_BATH(1)='../../Projects/Haima/swan_bathy.bot',
SWAN_NUMX(1)=390,
SWAN_NUMY(1)=285,
CARTESIAN(1)=0,

> 

The size of ROMS model:
> Lm == 388 ! Number of I-direction INTERIOR RHO-points -2
Mm == 283 ! Number of J-direction INTERIOR RHO-points -2
N == 16 ! Number of vertical levels
ND == 0 ! Number of wave directional bins

> 

Please help me to solve this problem.
Thank you in advance.

**Comment by jcwarner-usgs** [comment]
All these models want information in a different way, and it can be confusing.
ROMS wants to list the Lm and Mm in the ocean.in like you have it (#rho points -2).
SWAN actually wants the number of spaces, so if you have the same roms and swan grids (like you do) then the swan input file needs one less.  So you need to change
CGRID CURVILINEAR 390 285 
to
CGRID CURVILINEAR 389 284
in 5 places.
Did you also get any SWAN Err* files?

**Comment by Ntmanh18196** [comment]
Hi John,
If I change 
CGRID CURVILINEAR 390 285
to
CGRID CURVILINEAR 389 284
in 5 places.
I got this Err:
Error            : 3 comp. grid points on one line
Error            : Grid angle <0 or >180 degrees
Error            : Grid angle <0 or >180 degrees
Error            : Grid angle <0 or >180 degrees
Error            : Grid angle <0 or >180 degrees

**Comment by jcwarner-usgs** [comment]
ok. not sure. can you post the entire INPUT file. 
how did you create the swan grd file?

**Comment by Ntmanh18196** [comment]
Hi John,
I attach all of the input files in the below. 
Besides, in term of the way to create the SWAN grid, I use the  roms2swan.m program.

[coupling_haima.txt](https://github.com/jcwarner-usgs/COAWST/files/6134171/coupling_haima.txt)
[ocean_haima.txt](https://github.com/jcwarner-usgs/COAWST/files/6134172/ocean_haima.txt)
[scrip_coawst_haima.txt](https://github.com/jcwarner-usgs/COAWST/files/6134173/scrip_coawst_haima.txt)
[swan_haima.txt](https://github.com/jcwarner-usgs/COAWST/files/6134174/swan_haima.txt)
[namelist.input.txt](https://github.com/jcwarner-usgs/COAWST/files/6134306/namelist.input.txt)

**Comment by jcwarner-usgs** [comment]
ok a couple of things.

-your roms grid is 390 x 285, right?  the number of rho points?  size(h) = 390 285.

-lets try to just run swan by itself.  something seems odd.
set the project.h to just say  #define SWAN_MODEL
./coawst.bash -j 4
and when it is done, run it as
mpirun -np X ./coawstM swan_haima.txt
and lets see if that runs.  it should need " 389 284 " for the grid sizes for swan_haima.txt.

-if that works , then we need to redo scrip using
SWAN_COORD(1)='../../Projects/Haima/swan_coord.grd',
SWAN_BATH(1)='../../Projects/Haima/swan_bathy.bot',
SWAN_NUMX(1)=390,
SWAN_NUMY(1)=285,
CARTESIAN(1)=0,

-then rebuild the roms+swan+wrf and lets see what that gives.
-j

**Comment by Ntmanh18196** [comment]
Hi John,
Thank you for your helpful suggestions. 
I've changed my script like:
SWAN_COORD(1)='../../Projects/Haima/swan_coord.grd',
SWAN_BATH(1)='../../Projects/Haima/swan_bathy.bot',
SWAN_NUMX(1)=390,
SWAN_NUMY(1)=285,
CARTESIAN(1)=0,
and my SWAN's namelist:
&& KEYWORD TO CREATE WIND GRID &&
&INPGRID WIND REGULAR 96.9742 -2.3665 0 389 284 0.2 0.2 EXC 9.999000e+003 &
&      NONSTATIONARY 20161017.000000 6 HR 20161021.000000
WIND 5. 25.
my model can run successfully.
However, I run model with the 2D Spec files, I got the problem:
> forrtl: severe (194): Run-Time Check Failure. The variable 'bcfile_$DORDER' is being used in 'swanpre2.f90(3963,23)' without being defined

I've tried recompile model with "FFLAGS += -check uninit" option, it still failed. 
Can you kindly help me to solve this problem?

**Comment by jcwarner-usgs** [comment]
we just put in a correction for that, but maybe you dont have it or the ccorection is in the wrong place.  can you send the swanpre2.f90 file?

**Comment by Ntmanh18196** [comment]
Hi John,
Here is my swanpre2.f90 file 
[swanpre2.f90.txt](https://github.com/jcwarner-usgs/COAWST/files/6174810/swanpre2.f90.txt)

**Comment by jcwarner-usgs** [comment]
can you do an update, and make sure you get a new version of swanpre2.F?
then try it again.  we just added DORDER setting to make it a value of 0 if not used.  some compilers automatically set new vars to be 0, and some do not.  can you give this a try? -j

**Comment by jcwarner-usgs** [comment]
can u try this swanpre2 again?  i think the update had not made  it to git, but it should be there now.

**Comment by Ntmanh18196** [comment]
Hi John,
I've tried the swanpre2 file from this site (https://code.usgs.gov/coawstmodel/COAWST/-/tree/master/SWAN/Src) and recompiled with using FFLAGS += -check uninit option and without this option.
However, the error "forrtl: severe (194): Run-Time Check Failure. The variable 'bcfile_$DORDER' is being used in 'swanpre2.f90(3963,23)' without being defined" still occurred.

**Comment by jcwarner-usgs** [comment]
get the code from this site
https://github.com/jcwarner-usgs/COAWST/tree/master/SWAN/Src

**Comment by Ntmanh18196** [comment]
Hi John,
I got the swanpre2 file from your site, however, my model still failed with and without option "FFLAGS += -check uninit"
My log file displayed the error like that:
forrtl: severe (194): Run-Time Check Failure. The variable 'bcfile_$DORDER' is being used in 'swanpre2.f90(3965,23)' without being defined

**Comment by jcwarner-usgs** [comment]
did this get resolved?
