### ISSUE TITLE
A problem about compiling COAWST (./coawst.bash)

### ISSUE THREAD

**Issue by SamLG19940814** [DOI-USGS/COAWST#26]
Hi,

The last few lines of coawst.log, which is the below information, is generated when compiling COAWST (./coawst.bash).  It seems that it has a trouble about master.f90.  Please help me deal with this problem.

/usr/bin/cpp -P -traditional-cpp -w           -DMPI -DLINUX -DX86_64 -DIFORT -D'ROOT_DIR="/work/07687/samlg/stampede2/realcase/COAWST"' -DSOUDELOR -D'HEADER="soudelor.h"' -D'ROMS_HEADER="/work/07687/samlg/stampede2/realcase/COAWST/Projects/Soudelor/soudelor.h"' -DNestedGrids= -D'ANALYTICAL_DIR="/work/07687/samlg/stampede2/realcase/COAWST/Projects/Soudelor"' -D'MY_ANALYTICAL="on"' -D'SVN_URL=""' -D'SVN_REV=""' -IROMS/Include -I/work/07687/samlg/stampede2/realcase/COAWST/Projects/Soudelor -IROMS/Nonlinear -IROMS/Nonlinear/Biology -IROMS/Nonlinear/Sediment -IROMS/Nonlinear/Wec -IROMS/Nonlinear/Vegetation -IROMS/Utility -IROMS/Drivers -IROMS/Functionals -I/work/07687/samlg/stampede2/realcase/COAWST/Projects/Soudelor -IMaster -ICompilers -D'HEADER_DIR="/work/07687/samlg/stampede2/realcase/COAWST/Projects/Soudelor"'  Master/master.F > Build/master.f90
ROMS/Bin/cpp_clean Build/master.f90
cd ./Build; /opt/intel/compilers_and_libraries_2017.4.196/linux/mpi/intel64/bin/mpif90 -c -fp-model precise -ip -O3 -traceback -check uninit -I/work/07687/samlg/stampede2/realcase/COAWST/Lib/MCT/include -I/work/07687/samlg/stampede2/realcase/COAWST//WRF/main -I/work/07687/samlg/stampede2/realcase/COAWST//WRF/external/esmf_time_f90 -I/work/07687/samlg/stampede2/realcase/COAWST//WRF/frame -I/work/07687/samlg/stampede2/realcase/COAWST//WRF/share master.f90
master.f90(22): error #7002: Error in opening the compiled module file.  Check INCLUDE paths.   [MODULE_WRF_TOP]
      USE module_wrf_top, ONLY : wrf_init
----------^
master.f90(22): error #6580: Name in only-list does not exist.   [WRF_INIT]
      USE module_wrf_top, ONLY : wrf_init
---------------------------------^
master.f90(23): error #6580: Name in only-list does not exist.   [WRF_RUN]
      USE module_wrf_top, ONLY : wrf_run
---------------------------------^
master.f90(24): error #6580: Name in only-list does not exist.   [WRF_FINALIZE]
      USE module_wrf_top, ONLY : wrf_finalize
---------------------------------^
compilation aborted for master.f90 (code 1)
make: *** [Build/master.o] Error 1

**Comment by SamLG19940814** [comment]
Sorry for forgetting to attach coawst.bash file.
[coawst.txt](https://github.com/jcwarner-usgs/COAWST/files/6130807/coawst.txt)

**Comment by jcwarner-usgs** [comment]
the problem probably occurred way before this, so can you attach a complete build.log.
you can do something like
script build.log
./coawst.bash
exit 
and then send the build.log file here

**Comment by SamLG19940814** [comment]
Sorry for not attaching the log file. 
Thanks for your help.

[coawst.log](https://github.com/jcwarner-usgs/COAWST/files/6131383/coawst.log)

**Comment by jcwarner-usgs** [comment]
Hey! i might have a bug here. When i compile mct_coupler_params first, i do not know yet if the WRF has moving grids, so the -DMOVE_NESTS is not activated yet.  this is my fault.  can u do me a favor and try this:

edit Master/mct_coupler_params.F and put comments on the ifdef MOVE_NESTS.  this will need 4 comment (!) symbols:

change 
# ifdef MOVE_NESTS
!  If WRF has a moving nest then we need to keep some information.
      integer, dimension(:), pointer :: par_grid_ratio
      integer, dimension(:), pointer :: full_Isize
      integer, dimension(:), pointer :: full_Jsize
      integer, dimension(:), pointer :: parent_id
      integer, dimension(:), pointer :: moving_nest_istart
      integer, dimension(:), pointer :: moving_nest_jstart
# endif
--- to ---
!# ifdef MOVE_NESTS
!  If WRF has a moving nest then we need to keep some information.
      integer, dimension(:), pointer :: par_grid_ratio
      integer, dimension(:), pointer :: full_Isize
      integer, dimension(:), pointer :: full_Jsize
      integer, dimension(:), pointer :: parent_id
      integer, dimension(:), pointer :: moving_nest_istart
      integer, dimension(:), pointer :: moving_nest_jstart
!# endif

and change

# ifdef MOVE_NESTS
! If WRF has a moving nest, for now, it has to be the last grid.
      allocate (par_grid_ratio(Natm_grids))
      allocate (full_Isize(Natm_grids))
      allocate (full_Jsize(Natm_grids))
      allocate (parent_id(Natm_grids))
      allocate (moving_nest_istart(Natm_grids))
      allocate (moving_nest_jstart(Natm_grids))
# endif
--- to ---
!# ifdef MOVE_NESTS
! If WRF has a moving nest, for now, it has to be the last grid.
      allocate (par_grid_ratio(Natm_grids))
      allocate (full_Isize(Natm_grids))
      allocate (full_Jsize(Natm_grids))
      allocate (parent_id(Natm_grids))
      allocate (moving_nest_istart(Natm_grids))
      allocate (moving_nest_jstart(Natm_grids))
!# endif

./coawst.bash -nocleanwrf -noclean

-j

**Comment by SamLG19940814** [comment]
Thank you for replying me so quickly.

I have put comments on the ifdef MOVE_NESTS (there are 4 comment symbols), but the compilation still abort for master.f90.  The attached file below is the log file.  Please do me a favor and deal with this problem.

[coawst.log](https://github.com/jcwarner-usgs/COAWST/files/6134363/coawst.log)

**Comment by SamLG19940814** [comment]
Thank you for replying me so quickly.

I have put comments on the ifdef MOVE_NESTS (there are 4 comment symbols), and the error disappears when compiling.
The attached file below is the coawst.log.  I'm not sure whether my compilation have succeeded.

[coawst.log](https://github.com/jcwarner-usgs/COAWST/files/6141649/coawst.log)

By the way, the path is Master/MCT_coupler/mct_coupler_params.F instead of Master/mct_coupler_params.F, right?

**Comment by SamLG19940814** [comment]
Thank you for replying me so quickly.

I have put comments on the ifdef MOVE_NESTS (there are 4 comment symbols), but the compilation still abort (This time is for mod_coupler_iounits.f90).  The attached file below is the coawst.log.  

[coawst.log](https://github.com/jcwarner-usgs/COAWST/files/6142883/coawst.log)

By the way, the path is Master/MCT_coupler/mct_coupler_params.F instead of Master/mct_coupler_params.F, right?

---------------------

The last few lines of the coawst.log:

mod_coupler_iounits.f90(14): error #7002: Error in opening the compiled module file.  Check INCLUDE paths.   [MCT_COUPLER_PARAMS]
      USE mct_coupler_params
----------^
mod_coupler_iounits.f90(34): error #6404: This name does not have a type, and must have an explicit type.   [NOCN_GRIDS]
      allocate (O2Aname(Nocn_grids,Natm_grids))
------------------------^
mod_coupler_iounits.f90(34): error #6385: The highest data type rank permitted is INTEGER(KIND=8).   [NOCN_GRIDS]
      allocate (O2Aname(Nocn_grids,Natm_grids))
------------------------^
mod_coupler_iounits.f90(34): error #6404: This name does not have a type, and must have an explicit type.   [NATM_GRIDS]
      allocate (O2Aname(Nocn_grids,Natm_grids))
-----------------------------------^
mod_coupler_iounits.f90(34): error #6385: The highest data type rank permitted is INTEGER(KIND=8).   [NATM_GRIDS]
      allocate (O2Aname(Nocn_grids,Natm_grids))
-----------------------------------^
mod_coupler_iounits.f90(35): error #6385: The highest data type rank permitted is INTEGER(KIND=8).   [NATM_GRIDS]
      allocate (A2Oname(Natm_grids,Nocn_grids))
------------------------^
mod_coupler_iounits.f90(35): error #6385: The highest data type rank permitted is INTEGER(KIND=8).   [NOCN_GRIDS]
      allocate (A2Oname(Natm_grids,Nocn_grids))
-----------------------------------^
compilation aborted for mod_coupler_iounits.f90 (code 1)
make: *** [Build/mod_coupler_iounits.o] Error 1
make: *** Waiting for unfinished jobs....

**Comment by SamLG19940814** [comment]
Hi,

I downloaded the new COAWST file you had updated few days ago and tried to compile it.
There are less "error" words in the log file compared to the previous one, but there are so many "undefined reference" in the log file.
The below file is the log file.  Can you again do me a favor to check what happened during the compilation?
[coawst.log](https://github.com/jcwarner-usgs/COAWST/files/6206429/coawst.log)

**Comment by jcwarner-usgs** [comment]
all of those errors are associated with netcdf.  they all say stuff like:
"undefined reference to `netcdf_mp_nf90_open_'" ....
i think you need to have more libs listed.  I see:
mpif90 -fp-model precise   ....      -L/opt/apps/intel17/netcdf/4.3.3.1/x86_64/lib -lnetcdf 

usually there are -libnetcdf and -libnetcdff  (2f's)
so this can be set in several ways.

1) in the coawst.bash, did you set USE_NETCDF4=on 
that will make the call to use nf_config to set the libs.

0r 2) alternatively,  If you are using Linux and intel, look at the file Compilers/Linux-ifort.mk and you can see
ifdef USE_NETCDF4
        NF_CONFIG ?= nf-config
    NETCDF_INCDIR ?= $(shell $(NF_CONFIG) --prefix)/include
             LIBS += $(shell $(NF_CONFIG) --flibs)
           INCDIR += $(NETCDF_INCDIR) $(INCDIR)
else
    NETCDF_INCDIR ?= /opt/intelsoft/serial/netcdf3/include
    NETCDF_LIBDIR ?= /opt/intelsoft/serial/netcdf3/lib
      NETCDF_LIBS ?= -lnetcdf
             LIBS += -L$(NETCDF_LIBDIR) $(NETCDF_LIBS)
           INCDIR += $(NETCDF_INCDIR) $(INCDIR)
endif

you may need to edit this and use
      NETCDF_LIBS ?= -lnetcdf -lnetcdff

give one of those options a try.
-j

**Comment by SamLG19940814** [comment]
Thank you so much for your guidance.
I have successfully compiled COAWST without any error (there is an error regarding wrf.main, but it's ok according to the COAWST user manual)

**Comment by jcwarner-usgs** [comment]
glad it is working.
-j
