### ISSUE TITLE
Fatal error in MPI_Send:

### ISSUE THREAD

**Issue by Ntmanh18196** [DOI-USGS/COAWST#27]
Hi John,
I got the problem when I ran the COAWST model with ROMS+WRF+SWAN option, which is displayed in the below:

> Fatal error in MPI_Send: Other MPI error, error stack:
MPI_Send(173)..................: MPI_Send(buf=0x47a3d50, count=4, MPI_INTEGER, dest=0, tag=31, comm=0xc400002c) failed
MPIDI_EagerContigShortSend(262): failure occurred while attempting to send an eager message
MPIDI_CH3_iStartMsg(36)........: Communication error with rank 0

The detail of COAWST error and out was attached in this post. Please help me to solve this problem.
Thanks you in advance.
[COAWST.err.txt](https://github.com/jcwarner-usgs/COAWST/files/6145658/COAWST.err.txt)
[coawst.out.txt](https://github.com/jcwarner-usgs/COAWST/files/6145659/coawst.out.txt)

**Comment by jcwarner-usgs** [comment]
looks like system started to run, but then the communications stopped.  I see ROMS and WRF started, but i do not see any SWAN information.  maybe swan did not start.  Did you get any Err* files?  can you try with just roms+wrf to see if that works?

**Comment by Ntmanh18196** [comment]
Hi John,
I can run the model successfully with WRF+ROMS option. But I ran with WRF+ROMS+SWAN, the error appeared. 
I don't get the other error except the warning of SWAN model:
 COMPUTE NONSTAT 20170910.000000 6 HR 20170916.000000
 ** Warning          : Quadruplets will be updated per iteration
 ** Warning          : instead of per sweep. This will increase
 ** Warning          : amount of internal memory with a factor 2

**Comment by jcwarner-usgs** [comment]
it seems that something is going on with swan.  it might just be a path issue, not sure.
did you get any files that start with Err? can you look in the PRINT files to see if there is anything else strange.
maybe try to run swan by itself.
compile with just #define SWAN_MODEL
and run it with
mpirun -np X ./coawstM swan_input_file_name

-j

**Comment by Ntmanh18196** [comment]
Hi John,
Following your suggestion, I've been compiling COAWST with only SWAN model. After running the model, I got the error like this:
   ** Error            : It is not recommended to use quadruplets
 ** Error            : in combination with zero wind conditions.
 ** No start of computation because of error level:  2
 ** To ignore this error, change [maxerr] with the SET command
I also attach 2 error files in this post.
 
[Errfile01.txt](https://github.com/jcwarner-usgs/COAWST/files/6153327/Errfile01.txt)
[PRINT01.txt](https://github.com/jcwarner-usgs/COAWST/files/6153328/PRINT01.txt)

**Comment by jcwarner-usgs** [comment]
ok a couple of things here.  SWAN alone needs winds, and you are not letting it know what winds to use.  you can do that in several ways.  but for now, lets just do this. comment out a few lines and just give a simple wind command

&& KEYWORD TO CREATE WIND GRID &&
& INPGRID WIND REGULAR 96.9742 -2.3665 0 389 285 0.2 0.2 EXC 9.999000e+003 &
&       NONSTATIONARY 20170910.000000 6 HR 20170916.000000
WIND 5. 25.

and see if that works.  it most likely will. 
then we need to go back to the coupled simulations. can you do wrf+swan and lets see if that goes?  sorry to make you try different things here.

**Comment by Ntmanh18196** [comment]
HI John,
Thank you for your reply.
I've changed my swan's namelist according your suggestion to like that:
`MODE NONSTATIONARY TWODIMENSIONAL
SET DEPMIN 0.1 INRHOG 1 NAUTICAL PWTAIL 5
COORDINATES SPHERICAL

&& KEYWORD for number of nested SWAN grids.
NSGRIDS 1

&& KEYWORDS TO CREATE AND READ COMPUTATIONAL GRID &&
CGRID CURVILINEAR 389 285 EXC 9.999000e+003 9.999000e+003 CIRCLE 36 0.04 1.0 24
READGRID COORDINATES 1 'Projects/Doksuri/swan_coord.grd' 4 0 0 FREE

&& KEYWORDS TO CREATE AND READ BATHYMETRY GRID &&
INPGRID BOTTOM CURVILINEAR 0 0 389 285 EXC 9.999000e+003
READINP BOTTOM 1 'Projects/Doksuri/swan_bathy.bot' 4 0 FREE

&& KEYWORD TO CREATE CURRENT GRID &&
INPGRID CURRENT CURVILINEAR 0 0 389 285 EXC 9.999000e+003 &
       NONSTATIONARY 20170910.000000 6 DAY 20170916.000000

&& KEYWORD TO CREATE WATER LEVEL GRID &&
INPGRID WLEV CURVILINEAR 0 0 389 285 EXC 9.999000e+003 &
       NONSTATIONARY 20170910.000000 6 DAY 20170916.000000

&& KEYWORD TO CREATE BOTTOM FRIC GRID &&
INPGRID FRIC CURVILINEAR 0 0 389 285 EXC 9.999000e+003 &
       NONSTATIONARY 20170910.000000 6 DAY 20170916.000000

&& KEYWORD TO CREATE WIND GRID &&
&INPGRID WIND REGULAR 96.9742 -2.3665 0 389 285 0.2 0.2 EXC 9.999000e+003 &
&      NONSTATIONARY 20170910.000000 6 HR 20170916.000000

& Boundary files  ****************************************
& 2D Spec Boundary files  ****************************
BOUND SHAPESPEC JONSWAP MEAN DSPR DEGREES
BOUNDSPEC SEGMENT IJ    0    0    0  285  CONSTANT PAR  0.1  20.0    0.0  15
BOUNDSPEC SEGMENT IJ    0    0  389    0  CONSTANT PAR  0.1  20.0    0.0  15
BOUNDSPEC SEGMENT IJ  389    0  389  285  CONSTANT PAR  0.1  20.0    0.0  15
BOUNDSPEC SEGMENT IJ    0  285  389  285  CONSTANT PAR  0.1  20.0    0.0  15
& Restart name **********************************

&INIT
INIT_DEFAULT

& PHYSICS  ****************************************
BREAKING CONSTANT 1.0 0.73
FRICTION MADSEN 0.05
&OFF QUAD
GEN3 KOMEN
WCAP KOM 2.36E-5 3.02E-3 2.0 1.0 1.0
PROP BSBT

BLOCK 'COMPGRID' NOHEADER 'Doksuri_hsig.mat'   LAY 4 HSIGN 1.  OUTPUT 20170910.000000 1 HR
BLOCK 'COMPGRID' NOHEADER 'Doksuri_xp.mat'     LAY 4 XP 1.
BLOCK 'COMPGRID' NOHEADER 'Doksuri_yp.mat'     LAY 4 YP 1.
BLOCK 'COMPGRID' NOHEADER 'Doksuri_wind.mat'   LAY 4 WIND 1.   OUTPUT 20170910.000000 1 HR
BLOCK 'COMPGRID' NOHEADER 'Doksuri_hsig.nc'    LAY 4 HSIGN 1.  OUTPUT 20170910.000000 1 HR
RESTART 'swan_rst.dat' FREE 1 HR

&COMPUTE STAT 20170910.000000
COMPUTE NONSTAT 20170910.000000 6 HR 20170916.000000

HOTFILE 'Doksuri_init.hot'

STOP`

However,  I still got the error:
 `COMPUTE NONSTAT 20170910.000000 6 HR 20170916.000000
 ** Error            : It is not recommended to use quadruplets
 ** Error            : in combination with zero wind conditions.
 ** No start of computation because of error level:  2
 ** To ignore this error, change [maxerr] with the SET command
 ** No continuation of computation because of error level:  2
 ** No continuation of computation because of error level:
`

**Comment by jcwarner-usgs** [comment]
you did not add the:
WIND 5. 25.
this is telling it wind at 5mps from 25 deg north.

**Comment by Ntmanh18196** [comment]
Hi John,
Thank you very much. After I add the set-up in my namelist, it can work for my case.
SWAN grid   1 is preparing computation

+time 20170910.060000   , step      1; iteration    1; sweep 1 grid   1
+time 20170910.060000   , step      1; iteration    1; sweep 2 grid   1
+time 20170910.060000   , step      1; iteration    1; sweep 3 grid   1
+time 20170910.060000   , step      1; iteration    1; sweep 4 grid   1
+time 20170910.120000   , step      2; iteration    1; sweep 1 grid   1

**Comment by jcwarner-usgs** [comment]
ok good. so now we need to add WRF (or ROMS) but only one. lets take small steps.
so do SWAN+WRF or SWAN+ROMS.  
-j

**Comment by Ntmanh18196** [comment]
Hi John,
I got the error:
"get_sparse_matrix.f90(181): error #6404: This name does not have a type, and must have an explicit type.   [R8]
        sparse_weights_main(1)=0.0_r8
----------------------------------^
get_sparse_matrix.f90(181): error #6975: A kind-param must be a digit-string or a scalar-int-constant-name.   [R8]
        sparse_weights_main(1)=0.0_r8
----------------------------------^
compilation aborted for get_sparse_matrix.f90 (code 1)
make: *** [Build/get_sparse_matrix.o] Error 1"
when I compiled the WRF+SWAN option.
Here is my .h file:
`/*
** svn $Id: sandy.h 25 2007-04-09 23:43:58Z jcwarner $
*******************************************************************************
** Copyright (c) 2002-2007 The ROMS/TOMS Group                               **
**   Licensed under a MIT/X style license                                    **
**   See License_ROMS.txt                                                    **
*******************************************************************************
**
** Options for Sandy Test.
**
** Application flag:   SANDY
*/

#undef ROMS_MODEL
#undef NESTING
#define WRF_MODEL
#define SWAN_MODEL
#undef  WW3_MODEL
#define MCT_LIB
#undef MCT_INTERP_OC2AT
#define MCT_INTERP_WV2AT
#undef MCT_INTERP_OC2WV

#if defined WRF_MODEL && (defined SWAN_MODEL || defined WW3_MODEL)
# define DRAGLIM_DAVIS
# define COARE_TAYLOR_YELLAND
#endif


/* Grid and Initial */
# define MASKING

/* Forcing */
# ifdef WRF_MODEL
#  undef  BULK_FLUXES
#  undef ATM2OCN_FLUXES
#  undef  ANA_SSFLUX
#  undef  LONGWAVE_OUT
# else
#  define BULK_FLUXES
# endif
# define ANA_NUDGCOEF
# define ATM_PRESS
# define ANA_BTFLUX
# define ANA_BSFLUX
# define ANA_BPFLUX
# define ANA_SPFLUX
# define ANA_SRFLUX
# define EMINUSP
# define SOLAR_SOURCE

/* Turbulence closure */
# define GLS_MIXING
# undef  MY25_MIXING
# define LIMIT_VDIFF
# define LIMIT_VVISC

# if defined GLS_MIXING || defined MY25_MIXING
#  define KANTHA_CLAYSON
#  define N2S2_HORAVG
#  define RI_SPLINES
#  define CRAIG_BANNER
#  define CHARNOK
# endif

# define SSH_TIDES
# define UV_TIDES
# define RAMP_TIDES
# define ANA_FSOBC
# define ANA_M2OBC

/* Output */
# undef DIAGNOSTICS_UV
# undef DIAGNOSTICS_TS`
Can you help to fix this problem?
Thank you.

**Comment by jcwarner-usgs** [comment]
ok i just did an update to correct this issue.  can you update and try again?
-j

**Comment by Ntmanh18196** [comment]
Hi John,
Thank you very much for your reply.
I could run the model but it stopped after some minutes. 
My log file reported that:

> DIAG speed trouble    20.0042425625716
 Found Error: 01   Line: 351      Source: ROMS/Nonlinear/main3d.F
 Found Error: 01   Line: 332      Source: ROMS/Drivers/nl_ocean.h
 Blowing-up: Saving latest model state into  RESTART file
     REASON: MaxSpeed =  2.0E+01
      WRT_RST     - wrote re-start    fields (Index=1,1) in record = 0000001

Please help me to fix this problem.
Thank you in advance!

**Comment by jcwarner-usgs** [comment]
so now this is in your court.  You need to save the output frequently, look at where the model is having problems. is it at an open boundary, at the land/sea interface, from the atm forcing??  you need to look at that restart file.  maybe reduce your time step to save more often just to see what is happening.

**Comment by Ntmanh18196** [comment]
Hi John,
Can you kindly explain more detail for me?
I attach my ocean.in and log file in the below. 
At the moment, I use dt =4.0 and my output history, average, diagnostic files are created after 6.0h.
According to your suggestion, I must change my output to 3h or something like that, right?
[ocean_mangkhut.in.txt](https://github.com/jcwarner-usgs/COAWST/files/6198311/ocean_mangkhut.in.txt)
[COAWST.out.txt](https://github.com/jcwarner-usgs/COAWST/files/6198322/COAWST.out.txt)

**Comment by jcwarner-usgs** [comment]
this is something that you need to figure out. 
Your simulation ran for 2 hours:

 1950 2018-09-12 02:10:00.00  5.185066E-03  2.319661E+04  2.319662E+04  1.276614E+17
                     (185,051,01)  8.118571E-06  1.971663E-05  1.023848E-01  2.000424E+01
 DIAG speed trouble    20.0042425625716     

and then the currents got big somewhere. It wrote the fields in the rst file. Start out looking at that file. What does not look correct?  Where are the currents big?  is it from the forcing, density, winds, boundary condition?? there are many things that can happen. So you need to dig in.  Save the output to write out every 20 minutes (that would give you 6 or so time steps to start looking at.)  try to figure out where the currents are getting large?

**Comment by Ntmanh18196** [comment]
Hi John,
I find the warning on the PRINT file of SWAN model:
`+time 20180912.060000   , step      1; iteration    1; sweep 1 grid   1
+time 20180912.060000   , step      1; iteration    1; sweep 2 grid   1
+time 20180912.060000   , step      1; iteration    1; sweep 3 grid   1
+time 20180912.060000   , step      1; iteration    1; sweep 4 grid   1
 not possible to compute, first iteration
  ** WARNING : Differences in wave height at the boundary
 Relative difference between input and computation >=   0.10`
This is the problem which caused my bowing-up of my model, isn't it?

**Comment by jcwarner-usgs** [comment]
maybe, not sure.  Suggest you look at the ROMS his files. Are you writing out the Hwave?  what does it look like?  Are the wave heights what you expect to see.

**Comment by Ntmanh18196** [comment]
I have a quite stupid question is that how do I find the current variable in the ocean_rst.nc file?  I can not see this variables in this file.
In addition, I plot Uwave, vwave, ubar, vbar variables in the ocean_rst file and I don't find any weird problem.
![Fig1](https://user-images.githubusercontent.com/38093402/112516739-2b0b4080-8dca-11eb-8f60-94362774e123.PNG)
![fig2](https://user-images.githubusercontent.com/38093402/112516743-2c3c6d80-8dca-11eb-9359-13a6b8a58d8d.PNG)
![fig3](https://user-images.githubusercontent.com/38093402/112516747-2cd50400-8dca-11eb-9914-80f42c5a97ff.PNG)
![fig4](https://user-images.githubusercontent.com/38093402/112516748-2d6d9a80-8dca-11eb-83fb-e594d1663ea1.PNG)

**Comment by jcwarner-usgs** [comment]
the rst file only saves information needed to restart.  the his file can save information, but you need to se those output variables. For example in the ocean.in:
Hout(idUvel) == T      ! u                  3D U-velocity
Hout(idVvel) == T      ! v                  3D V-velocity
....
Hout(idWamp) == T     ! Hwave              wave height
Hout(idWlen) == T     ! Lwave              wave length-mean

not sure what time steps those are.  sometimes that error:
1950 2018-09-12 02:10:00.00 5.185066E-03 2.319661E+04 2.319662E+04 1.276614E+17
(185,051,01) 8.118571E-06 1.971663E-05 1.023848E-01 2.000424E+01
DIAG speed trouble 20.0042425625716

means that the currents were getting large near i=185, j=51, z=1.  look at the output at the last time step.  keep digging.

**Comment by Ntmanh18196** [comment]
Hi John,
I don't know exactly where the error came from, but after I use the smaller domain of WRF and ROMS model, the error didn't occur.
