### ISSUE TITLE
A compilation problem in the latest version of COAWST (there is no error in the previous version)

### ISSUE THREAD

**Issue by SamLG19940814** [DOI-USGS/COAWST#28]
Hi,

The below log file records the problems I have encountered. 
[coawst.log](https://github.com/jcwarner-usgs/COAWST/files/6165172/coawst.log)
It is strange that there is no error when I use the previous version (I forget the date of issue) of COAWST to compile, and the header file and bast file is totally the same.

Recently, I found that the code in Master/mct_coupler_params.F is slightly different between the latest and the previous version of COAWST.  There is no "MOVE_NESTS" in the previous code while there is in the latest code.  I guess that the problem exists in the setting of moving nests (I set 3 = vortex following during the COAWST compilation).  Can you do me a favor to fix this problem?

The header file: 
[soudelor.txt](https://github.com/jcwarner-usgs/COAWST/files/6165312/soudelor.txt)

The bash file: 
[coawst.txt](https://github.com/jcwarner-usgs/COAWST/files/6165305/coawst.txt)

**Comment by jcwarner-usgs** [comment]
i am working on this now.  this is the same as the other issue #26, so lets just keep it in that thread.
-j
