### ISSUE TITLE
1d index lies outside the boundaries provided in nctablemd.f90

### ISSUE THREAD

**Issue by Dooruk** [DOI-USGS/COAWST#29]
Hi John,

I'm running a coupled (ROMS+SWAN) simulation with three open boundaries.

It took about 7 hours to successfully complete a 20 days long simulation, however SWAN kept on running for another half an hour until it hit the walltime limit, 7.5 hours. When I look at the log file (attached the end part) I saw an error with the boundaries

**`1d index lies outside the boundaries provided in nctablemd.f90`**

The results look perfectly fine. I just conducted a short 12 hours long test simulation with the exact same setup, didn't get any errors. I am not sure what is happening.

I haven't encountered this error before during my simulations on different years with similar setups.

I will be submitting hundreds of jobs (ensemble runs), where this error might cause issues. Should I just comment out the part of the Fortran code in the source files?

Thanks!

[log.txt](https://github.com/jcwarner-usgs/COAWST/files/6185930/log.txt)

**Comment by jcwarner-usgs** [comment]
i have actually never seen that error before. not sure it is really an error. I think SWAN is writing data to a netcdf file. The values being written are compared to typical min/max values in nctablemd.F  and the 'error' is just saying that the written values are outside this range. I would look at the data and see if there is anything obviously out of range.
