### ISSUE TITLE
Error  gn=roms_getnplot_grid_rutgers(modelgrid,[theta_s theta_b Tcline N]);

### ISSUE THREAD

**Issue by Ntmanh18196** [DOI-USGS/COAWST#32]
Hi John,
I got the problem when I ran COAWST model with real-time data, which is displayed in the below:

> Error using matlab.graphics.axis.Axes/set
Value must be a 1x2 vector of numeric type in which the second element is larger than the first and may be Inf
Error in axis>LocSetLimits (line 283)
    set(ax,...
Error in axis (line 112)
                LocSetLimits(ax(j),cur_arg,names);
Error in pcolorjw (line 90)
        axis(lims);
Error in roms_getnplot_grid_rutgers (line 326)
    pcolorjw(grd.lon_rho,grd.lat_rho,grd.h)
Error in test4 (line 27)
gn=roms_getnplot_grid_rutgers(modelgrid,[theta_s theta_b Tcline N]);

The line 326 of the roms_getnplot_grid_rutgers program is:
`pcolorjw(grd.lon_rho,grd.lat_rho,grd.h)`

My controlling program is that:

> T1=floor(now+1); %start date
numdays=1;
dayFrequency=1;
% (3) Enter working directory (wdr)
wdr='E:\Matlab2'
% (4) Enter path and name of the ROMS grid (modelgrid)
modelgrid='ROMS_COAWST_grd1.nc'
gname_pre ='Mangkhut'
% (5) Enter grid vertical coordinate parameters --These need to be consistent with the ROMS setup. 
theta_s=10;
theta_b=0.4;
Tcline=50;
N=16;
Vtransform=1;
Vstretch=1;
%%%%%%%%%%%%%%%%%%%%%   END OF USER INPUT  %%%%%%%%%%%%%%%%%%%%%%%%%%
eval(['cd ',wdr])
tic
% Call to get HYCOM indices for the defined ROMS grid
%disp('getting roms grid, hycom grid, and overlapping indices')
%[gn, clm]=get_ijrg(url, modelgrid, theta_s, theta_b, Tcline, N, Vtransform, Vstretching);
disp('getting roms grid dimensions ...');
gn=roms_getnplot_grid_rutgers(modelgrid,[theta_s theta_b Tcline N]);
gn.Vtransform=1;
gn.Vstretching=1;
% call to create clm file
disp('going to create clm file')
   %org fn=updatclim_coawst_mw_12b_hycomorg(gn,[gname_pre,'_coawst_clm.nc'])
  fn=updatclim_coawst_mw_12b_hycomorg(gn,[gname_pre,'_coawst_clm.nc'])
% call to create boundary file
disp('going to create bdy file')
  updatbdry_coawst_mw(fn,gn,[gname_pre,'_coawst_bdy.nc'],wdr)
% Call to create the initial (ini) file
disp('going to create init file')
  updatinit_coawst_mwmodify(fn,gn,[gname_pre,'_coawst_ini.nc'],wdr)
%% Call to create the long climatology (clm) file
if numdays>1
    disp('going to create more days of clm and bnd files')
    if (ispc)
      eval(['!copy coawst_clm.nc coawst_clm_',datestr(T1,'yyyymmdd'),'.nc'])
      eval(['!copy coawst_bdy.nc coawst_bdy_',datestr(T1,'yyyymmdd'),'.nc'])
    else
      eval(['!cp coawst_clm.nc coawst_clm_',datestr(T1,'yyyymmdd'),'.nc'])
      eval(['!cp coawst_bdy.nc coawst_bdy_',datestr(T1,'yyyymmdd'),'.nc'])
    end
    for it=dayFrequency:dayFrequency:numdays-1      %1st day already created, NEED to set number of days at top!
        fname=['coawst_clm_',datestr(T1+it,'yyyymmdd'),'.nc']
        fn=updatclim_coawst_mw(T1+it,gn,fname,wdr,url)
        fname=['coawst_bdy_',datestr(T1+it,'yyyymmdd'),'.nc'];
        updatbdry_coawst_mw(fn,gn,fname,wdr)
    end
    %% get an organized list of dated files
    Dclm=dirsort('coawst_clm_*.nc');
    Dbdy=dirsort('coawst_bdy_*.nc');
    %names for merged climatology/boundary files
    fout='merged_coawst_clm.nc';
    foutb='merged_coawst_bdy.nc';
    %create netcdf files to merge climatology into
    create_roms_netcdf_clm_mwUL(fout,gn,length(Dclm));% converted to BI functions
    create_roms_netcdf_bndry_mwUL(foutb,gn,length(Dbdy));% converted to BI functions
    %% fill merged climatology files with data from each clm file
    % each file must contain only ONE time step
    %get variable names
    vinfo=ncinfo(fout);
    for nf=1:length(Dclm)
        fin=Dclm(nf).name;
        for nv=1:length({vinfo.Variables.Name})
            if length({vinfo.Variables(nv).Dimensions.Name})==4;                eval(['ncwrite(fout,''',vinfo.Variables(nv).Name,''',ncread(fin,''',vinfo.Variables(nv).Name,'''),[1 1 1 nf]);']);
            elseif length({vinfo.Variables(nv).Dimensions.Name})==3;
              eval(['ncwrite(fout,''',vinfo.Variables(nv).Name,''',ncread(fin,''',vinfo.Variables(nv).Name,'''),[1 1 nf]);']);
            elseif length({vinfo.Variables(nv).Dimensions.Name})==2;
                try                 eval(['ncwrite(fout,''',vinfo.Variables(nv).Name,''',ncread(fin,''',vinfo.Variables(nv).Name,'''),[1 nf]);']);
                catch
                    display([vinfo.Variables(nv).Name ' is a dimension and has already been written to the file.'])
                end
            elseif length({vinfo.Variables(nv).Dimensions.Name})==1;
                try
                    eval(['ncwrite(fout,''',vinfo.Variables(nv).Name,''',ncread(fin,''',vinfo.Variables(nv).Name,'''),[nf]);']);
                catch
                    display([vinfo.Variables(nv).Name ' is a dimension and has already been written to the file.'])
                end
            end
        end
    end

Please help me to resolve this problem.
Thank you very much!

**Comment by jcwarner-usgs** [comment]
this looks like an error from not being able to plot the grid.
which really means that the grid is not being read in correctly or something else.
do you know how to put break commands in matlab m files?  you could put a break 

on line 326 of the roms_getnplot_grid_rutgers program is:
pcolorjw(grd.lon_rho,grd.lat_rho,grd.h)

and see what the grd structure looks like.

**Comment by Ntmanh18196** [comment]
Hi John,
I've passed the former error which I posted in the last post. However, I got the error:
> Error using netcdflib
The number of input elements does not match the variable size.
Error in netcdf.putVar (line 88)
netcdflib(funcstr,ncid,varid,varargin{:});
Error in updatinit_coawst_mwmodify (line 252)
    eval(['netcdf.putVar(nc_init,tempid,',vars2d{i},');']);%set variable
Error in test4 (line 42)
   updatinit_coawst_mwmodify(fn,gn,[gname_pre,'_coawst_ini.nc'

The line 252 of the updatinit_coawst_mwmodify program is: 

> eval(['netcdf.putVar(nc_init,tempid,',vars2d{i},');']);%set variable

The structure of writing of 2D variables is that:

> %% 2D variables
for i=1:length(vars2d)
    eval(['tempclmid = netcdf.inqVarID(nc_clm,''',vars2d{i},''');']);%get id
    eval([vars2d{i},'=netcdf.getVar(nc_clm,tempclmid);']);%get data  
    eval(['tempid = netcdf.inqVarID(nc_init,''',vars2d{i},''');']);%get id
    zz=vars2d{i};  
    zz=zz(:,:,end);  
    vars2d{i}=zz;    %
    eval(['netcdf.putVar(nc_init,tempid,',vars2d{i},');']);%set variable
end 

Please help me to solve this problem!

**Comment by jcwarner-usgs** [comment]
ok. i tried to help fix this before, and you will need to find someone to help with your application.
at this point of the m file, the init_file has been created.  a few lines above it did:
create_roms_netcdf_init_mw(init_file,gn,Nbed,NNS,NCS,NVEG)

so you have an init file,  you just need to fill it with data.
Do you have anyone  there that can figure out how to fill a netcdf file with data?  this is a basic step that you need to know how to do.

**Comment by Ntmanh18196** [comment]
Hi John,
I found the error came from the netcdf.putVar program. I set the breakpoint at the line  eval(['netcdf.putVar(nc_init,tempid,',vars2d{i},');']);%set variable, and print to screen the value of vars2d{i} variable. The value of vars2d{i} with i =1 is just a string ('zeta') and the value of vars2d{i} on the "eval" command must be a zeta variable with 3 dimensions.
I've tried using the command "eval(['netcdf.putVar(nc_init,tempid,',zeta,');']);%set variable", however it reported that:
Error using horzcat
Dimensions of arrays being concatenated are not consistent.

Error in updatinit_coawst_mwmodify (line 254)
    eval(['netcdf.putVar(nc_init,tempid,',zeta,');']);%set variable

Can you kindly give me some suggestions?
Thank you very much!

**Comment by jcwarner-usgs** [comment]
there is probably a size mismatch here.  make it more simple to find the error:
for the %% 2D variables

instead of:
for i=1:length(vars2d)
    eval(['tempclmid = netcdf.inqVarID(nc_clm,''',vars2d{i},''');']);%get id
    eval([vars2d{i},'=netcdf.getVar(nc_clm,tempclmid);']);%get data   
    eval(['tempid = netcdf.inqVarID(nc_init,''',vars2d{i},''');']);%get id
    eval(['netcdf.putVar(nc_init,tempid,',vars2d{i},');']);%set variable
end

try:
tdata=ncread(nc_clm,'zeta');
ncwrite(nc_init,'zeta',tdata);
tdata=ncread(nc_clm,'ubar');
ncwrite(nc_init,'ubar',tdata);
tdata=ncread(nc_clm,'vbar');
ncwrite(nc_init,'vbar',tdata);

**Comment by Ntmanh18196** [comment]
Hi John,
 I've tried using your suggestion, however, it got the error:

Error using contains
First argument must be a string array, character vector, or cell array of character vectors.

Error in internal.matlab.imagesci.nc/openToRead (line 1265)
            if contains(this.Filename, '://')

Error in internal.matlab.imagesci.nc (line 121)
                    this.openToRead();

Error in ncread (line 61)
ncObj   = internal.matlab.imagesci.nc(ncFile);

Error in updatinit_coawst_mwmodify (line 252)
    tdata=ncread(nc_clm,'zeta');

**Comment by Ntmanh18196** [comment]
Hi John,
The error came from the difference of variable of clm file and init file. I have modified my program by converting the size of variable and it worked.
    tempclmid=netcdf.inqVarID(nc_clm,'zeta');%get id
    zeta=netcdf.getVar(nc_clm,tempclmid);%get data 
    dem=size(zeta);
    for i=1:dem(1)
        for j=1:dem(2)
    zz(i,j)=zeta(i,j);
        end
    end
    tempid=netcdf.inqVarID(nc_init,'zeta');%get id
    netcdf.putVar(nc_init,tempid,zz);%set variable
However, there are 7 variables in the init file so if we have a function do this job it will be more convenient.
If yes, can you help me resolve my idea?
Thank you for your help.

**Comment by jcwarner-usgs** [comment]
Yeah!! I am glad you got it to work!   The init file really only needs 1 time step, but the clm file can have more than 1.

I like your idea of creating a function. Yes that would be a good next step. This would be a great way for you to start developing your own tools for your approach. I am going to consider this ticket to be closed. I think it would be good for you to keep developing tools but I am not the best person to help with this. We provide a basic set of tools that have general functionality but you should modify the tools so that they work for you.  I am glad you got it to work.
