### ISSUE TITLE
coawst.bash compile error for coupled models

### ISSUE THREAD

**Issue by asuanda** [DOI-USGS/COAWST#33]
Hello John,

I am trying to compile COAWST on MacOS, using a conda environment. COAWST compiles when I make an example that is a single model (e.g., ROMS only), but when I try to compile coawst.bash for a coupled model (e.g., ROMS+SWAN), I get what looks like an MCT error (log attached). MCT appears to be functioning by itself (MCT test models), but any tips/suggestions much appreciated.

[coawst.log](https://github.com/jcwarner-usgs/COAWST/files/6427934/coawst.log)

**Comment by jcwarner-usgs** [comment]
i see
-I/Users/suandas/COAWST/Lib/MCT/include .... Nonexistent include directory
Does that directory exist?

**Comment by asuanda** [comment]
Yes, it exists

**Comment by jcwarner-usgs** [comment]
what does this return:

ls -ltr /Users/suandas/COAWST/Lib/MCT/include

**Comment by asuanda** [comment]
(coawst) C02DW07L0833:COAWST suandas$ ls -ltr /Users/suandas/COAWST/Lib/MCT/include
total 456
-rw-r--r--  1 suandas  37971631   492 May  5 10:25 m_chars.mod
-rw-r--r--  1 suandas  37971631  1148 May  5 10:25 m_die.mod
-rw-r--r--  1 suandas  37971631   336 May  5 10:25 m_dropdead.mod
-rw-r--r--  1 suandas  37971631   943 May  5 10:25 m_fccomms.mod
-rw-r--r--  1 suandas  37971631   480 May  5 10:25 m_filename.mod
-rw-r--r--  1 suandas  37971631   822 May  5 10:25 m_fileresolv.mod
-rw-r--r--  1 suandas  37971631   365 May  5 10:25 m_flow.mod
-rw-r--r--  1 suandas  37971631   601 May  5 10:25 m_indexbin_char.mod
-rw-r--r--  1 suandas  37971631   569 May  5 10:25 m_indexbin_integer.mod
-rw-r--r--  1 suandas  37971631   410 May  5 10:25 m_indexbin_logical.mod
-rw-r--r--  1 suandas  37971631  2116 May  5 10:25 m_inpak90.mod
-rw-r--r--  1 suandas  37971631   583 May  5 10:25 m_ioutil.mod
-rw-r--r--  1 suandas  37971631  2722 May  5 10:25 m_list.mod
-rw-r--r--  1 suandas  37971631  2011 May  5 10:25 m_mall.mod
-rw-r--r--  1 suandas  37971631  1292 May  5 10:25 m_mergesorts.mod
-rw-r--r--  1 suandas  37971631   871 May  5 10:25 m_mpif.mod
-rw-r--r--  1 suandas  37971631  2829 May  5 10:25 m_mpif90.mod
-rw-r--r--  1 suandas  37971631   570 May  5 10:25 m_mpout.mod
-rw-r--r--  1 suandas  37971631  2052 May  5 10:25 m_permuter.mod
-rw-r--r--  1 suandas  37971631   851 May  5 10:25 m_rankmerge.mod
-rw-r--r--  1 suandas  37971631   278 May  5 10:25 m_realkinds.mod
-rw-r--r--  1 suandas  37971631  4145 May  5 10:25 m_sortingtools.mod
-rw-r--r--  1 suandas  37971631   275 May  5 10:25 m_stdio.mod
-rw-r--r--  1 suandas  37971631  1995 May  5 10:25 m_string.mod
-rw-r--r--  1 suandas  37971631   392 May  5 10:25 m_strtemplate.mod
-rw-r--r--  1 suandas  37971631   523 May  5 10:25 m_traceback.mod
-rw-r--r--  1 suandas  37971631   727 May  5 10:25 m_zeit.mod
-rw-r--r--  1 suandas  37971631  3909 May  5 10:25 m_accumulator.mod
-rw-r--r--  1 suandas  37971631  1699 May  5 10:25 m_accumulatorcomms.mod
-rw-r--r--  1 suandas  37971631  4076 May  5 10:25 m_attrvect.mod
-rw-r--r--  1 suandas  37971631  2731 May  5 10:25 m_attrvectcomms.mod
-rw-r--r--  1 suandas  37971631  1613 May  5 10:25 m_attrvectreduce.mod
-rw-r--r--  1 suandas  37971631  1602 May  5 10:25 m_convertmaps.mod
-rw-r--r--  1 suandas  37971631   765 May  5 10:25 m_exchangemaps.mod
-rw-r--r--  1 suandas  37971631  3681 May  5 10:25 m_generalgrid.mod
-rw-r--r--  1 suandas  37971631  3557 May  5 10:25 m_generalgridcomms.mod
-rw-r--r--  1 suandas  37971631  1644 May  5 10:25 m_globalmap.mod
-rw-r--r--  1 suandas  37971631  2767 May  5 10:25 m_globalsegmap.mod
-rw-r--r--  1 suandas  37971631   931 May  5 10:25 m_globalsegmapcomms.mod
-rw-r--r--  1 suandas  37971631  1635 May  5 10:25 m_globaltolocal.mod
-rw-r--r--  1 suandas  37971631  1690 May  5 10:25 m_matattrvectmul.mod
-rw-r--r--  1 suandas  37971631  2023 May  5 10:25 m_mctworld.mod
-rw-r--r--  1 suandas  37971631  2685 May  5 10:25 m_merge.mod
-rw-r--r--  1 suandas  37971631  1566 May  5 10:25 m_navigator.mod
-rw-r--r--  1 suandas  37971631  2750 May  5 10:25 m_rearranger.mod
-rw-r--r--  1 suandas  37971631  2213 May  5 10:25 m_router.mod
-rw-r--r--  1 suandas  37971631  4216 May  5 10:25 m_sparsematrix.mod
-rw-r--r--  1 suandas  37971631  2024 May  5 10:25 m_sparsematrixcomms.mod
-rw-r--r--  1 suandas  37971631  1217 May  5 10:25 m_sparsematrixdecomp.mod
-rw-r--r--  1 suandas  37971631  5333 May  5 10:25 m_sparsematrixplus.mod
-rw-r--r--  1 suandas  37971631  2447 May  5 10:25 m_sparsematrixtomaps.mod
-rw-r--r--  1 suandas  37971631  2598 May  5 10:25 m_spatialintegral.mod
-rw-r--r--  1 suandas  37971631  2400 May  5 10:25 m_spatialintegralv.mod
-rw-r--r--  1 suandas  37971631  3293 May  5 10:25 m_transfer.mod

**Comment by jcwarner-usgs** [comment]
yeah, sorry.  that non existent include dir is the /usr/include
It is at the bottom i see the compiler is having trouble with the mct_coupler_params.  i think it is not adding the Build/mct* listing.  can you post the Compilers/*.mk file you are using?  do you know how to figure that out?
uname -s tells you the OS, and whatever compiler you set in the coawst.bash.

**Comment by asuanda** [comment]
[Darwin-gfortran.mk.txt](https://github.com/jcwarner-usgs/COAWST/files/6428585/Darwin-gfortran.mk.txt)

For some reason I had to make it a plain text to post to Github.

**Comment by jcwarner-usgs** [comment]
[Darwin-gfortran.mk.txt](https://github.com/jcwarner-usgs/COAWST/files/6429438/Darwin-gfortran.mk.txt)
can you try this one

**Comment by asuanda** [comment]
This one works! Single model (ducknc test) compiles and model runs. Multi-model (inlet coupling case) compiles and models both run. Thank you, John. I will take a closer look at the modifications you have made in this compiler script.
