### ISSUE TITLE
Real-time wave data

### ISSUE THREAD

**Issue by Ntmanh18196** [DOI-USGS/COAWST#34]
Hi John,
I'm interested in the real-time forecasting of COAWST model in your website (https://woodshole.er.usgs.gov/project-pages/cccp/public/COAWST.htm). However, in the ww3_swan_input.m program we use either partitions or gribs data and the date of these data has finished in May 2019.
The question I want to ask you is that what's kind of wave data do you have to create the BCs of SWAN model?
Thank you very much!

**Comment by jcwarner-usgs** [comment]
for hindcast:  i am working to update those ww3 to swan m files, hope to have that done soon.

for forecast:  we get WW3 data from here:
https://nomads.ncep.noaa.gov/dods/wave
and then interpolate the hwave, dwave, pwave to the swan grid boundary, and then create TPAR files.  The file format for the TPAR files is described in the SWAN manual.

**Comment by Ntmanh18196** [comment]
Hi John,
I don't see the data in your website, I find out 3 options, including info, dds and das. How do you download the data from this website?
In addition, the format of these data are different from the data from ftp://polar.ncep.noaa.gov/pub/history/waves, so we can not use the ww3_swan_input program.

**Comment by jcwarner-usgs** [comment]
the info tells you the name of the url to get the data via thredds server access.  that name will change each day, as it has the date in the url name. there are many ways to get the data via thredds, such as matlab or other tools. 

I just updated the m files to read ww3 data and create TPAR files, but these are only for use to get ww3 data from hindcasts.  see the information in the m files. You can use these tools as an approach to see how to read ww3 data via thredds. You would have to create your own tools to read the forecast data.
