### ISSUE TITLE
NETCDF output from SWAN

### ISSUE THREAD

**Issue by dickson2021** [DOI-USGS/COAWST#35]
May I know the latest version of COAWST v3.7 has fixed the issue of netcdf output for more than one grid under nested configuration.  I am having a nested configuration with coarse and fine grid coupling with ROMS in COAWST.  I would like to have separate SWAN outputs from coarse and fine grid in netcdf format when both are enabled in the .in files.  In the last version, an error was reported as  ""allocatable array already allocated" .    I did try the latest version v3.7 but only the coarse grid got output but not from the fine grid.  When I disabled the netcdf output from coarse and only want to have the output from fine grid.  However, nothing was output at all. 

Thank you

Dickson

**Comment by jcwarner-usgs** [comment]
yeah, sorry.  i have not corrected this issue. i think you can have netcdf for the coarse or for the child, but not both.  it is on the list.
However the output is typically written to the roms his files.  is there a reason you also want the swan output?  are there variables that are not in the coupling that you want written out?

**Comment by dickson2021** [comment]
I want the output of  SWELL (HSWELL) and Primary SWELL ( partition of sig. wave height  , PTHSign01, 02 ....etc ).  They are not in the his files.  In this latest version,  it is strange that I can only output the netcdf for coarse grid.  There is no netcdf output when I enable  netcdf for fine grid.   It was as you said that I could have netcdf for the coarse or for the child in the last version (v3.6).
I am also doing WWIII + ROMS coupling , why the sig wave heights written in his /qck not exactly the same as the  netcdf file output from WWIII itself. The results written in his/qck are smaller than those output direct from WWIII.         

Thanks a lot

**Comment by jcwarner-usgs** [comment]
you know you can output mat files on both swan grids, right?  so that can get you started.

**Comment by dickson2021** [comment]
Hi John,

Yes.  I can get mat files from both swan grids.  Any existing matlab script to covert them to nc files similar to those output from SWAN for ncl plotting. 

The problem below was fixed as I forgot to change the number of grid to 2  in SWAN.in file of coarse grid ( NSGRIDS 2 ).
"In this latest version, it is strange that I can only output the netcdf for coarse grid. There is no netcdf output when I enable netcdf for fine grid. "

Thank you

**Comment by jcwarner-usgs** [comment]
glad it worked.
for swan2roms, we had an m file to do that, but it used the old matlab netcdf style and would not work anymore.  we have not spent time to convert it to more recent netcdf in matlab.
