### ISSUE TITLE
Error in create_swanTpar_from_WW3

### ISSUE THREAD

**Issue by Ntmanh18196** [DOI-USGS/COAWST#36]
Hi John,
I got the error after a few day running the create_swanTpar_from_WW3 program, the detail of this issue is that:
We are adding 0 to the roms longitude - line 34 ww3gb_2TPAR.m
getting hs tp and dp for 20170901.0000
getting hs tp and dp for 20170901.0300
getting hs tp and dp for 20170901.0600
getting hs tp and dp for 20170901.0900
getting hs tp and dp for 20170901.1200
getting hs tp and dp for 20170901.1500
getting hs tp and dp for 20170901.1800
getting hs tp and dp for 20170901.2100
getting hs tp and dp for 20170902.0000
getting hs tp and dp for 20170902.0300
getting hs tp and dp for 20170902.0600
getting hs tp and dp for 20170902.0900
getting hs tp and dp for 20170902.1200
getting hs tp and dp for 20170902.1500
getting hs tp and dp for 20170902.1800
getting hs tp and dp for 20170902.2100
getting hs tp and dp for 20170903.0000
getting hs tp and dp for 20170903.0300
getting hs tp and dp for 20170903.0600
getting hs tp and dp for 20170903.0900
getting hs tp and dp for 20170903.1200
getting hs tp and dp for 20170903.1500
getting hs tp and dp for 20170903.1800
getting hs tp and dp for 20170903.2100
getting hs tp and dp for 20170904.0000
Error using netcdflib
The NetCDF library encountered an error during execution of 'open' function - 'I/O failure (NC_EIO)'.
If the data source was an  OPeNDAP URL, see the OPeNDAP Troubleshooting section in the Users Guide.
Error in netcdf.open (line 67)
        [varargout{:}] = netcdflib ( 'open', filename, varargin{1} );
Error in internal.matlab.imagesci.nc/openToRead (line 1278)
            this.ncRootid = netcdf.open(this.Filename,'NOWRITE');
Error in internal.matlab.imagesci.nc (line 121)
                    this.openToRead();
Error in ncread (line 61)
ncObj   = internal.matlab.imagesci.nc(ncFile);
Error in readww3_2TPAR (line 58)
  hs=double(squeeze(ncread(hsurl,'Significant_height_of_combined_wind_waves_and_swell_surface',[ig0
  jg0 tidx],[ig1-ig0+1 jg1-jg0+1 1])));
Error in create_swanTpar_from_WW3 (line 46)
readww3_2TPAR(modelgrid,yearww3,mmww3,ww3_grid,specpts)

Please help me to resolve this problem!
Thank you very much!

**Comment by jcwarner-usgs** [comment]
so when there is a problem , you can do this.
go here to access a lot of the NOAA data
https://www.ncei.noaa.gov/thredds-ocean/catalog.html
for the archived ww3 data , go here:
WAVEWATCH III® - Operational Wave Models/
then click on the year, mo  files, click gribs,
 multi_1.glo_30m.hs.201709.grb2
to make sure the file exists. you can click on it and access it, download if you want, etc.

i tried it with the mfiles and it worked for me.
...
getting hs tp and dp for 20170903.1500
getting hs tp and dp for 20170903.1800
getting hs tp and dp for 20170903.2100
getting hs tp and dp for 20170904.0000
getting hs tp and dp for 20170904.0300
getting hs tp and dp for 20170904.0600
getting hs tp and dp for 20170904.0900
getting hs tp and dp for 20170904.1200
getting hs tp and dp for 20170904.1500
getting hs tp and dp for 20170904.1800
getting hs tp and dp for 20170904.2100
getting hs tp and dp for 20170905.0000
getting hs tp and dp for 20170905.0300
getting hs tp and dp for 20170905.0600.....

so maybe your internet connection timed out.  try it again.
-j

**Comment by Ntmanh18196** [comment]
Hi John,
I don't know exactly where the error came from, but I run it successfully on HPC.
That's really strange. And it worked at the second time.
