### ISSUE TITLE
Fatal error in MPI_Send: Other MPI error, error stack:

### ISSUE THREAD

**Issue by Ntmanh18196** [DOI-USGS/COAWST#38]
Hi John,
I got the error when I ran the COAWST model with 3.7 version, which is displayed like that:
`Fatal error in MPI_Send: Other MPI error, error stack:
MPI_Send(173)..................: MPI_Send(buf=0x7ffde9abc638, count=1, MPI_INTEGER, dest=0, tag=3, MPI_COMM_WORLD) failed
MPIDI_EagerContigShortSend(262): failure occurred while attempting to send an eager message
MPIDI_CH3_iStartMsg(36)........: Communication error with rank 0`
In addition, I find out the another error:
`forrtl: severe (174): SIGSEGV, segmentation fault occurred
Image              PC                Routine            Line        Source             
coawstM            0000000003C1C1DA  Unknown               Unknown  Unknown
libpthread-2.17.s  00002B353A86F5D0  Unknown               Unknown  Unknown
coawstM            0000000000BD1AB4  swboun_                  3546  swanpre2.f90
coawstM            0000000000ADDE5E  swread_                  1851  swanpre1.f90
coawstM            0000000000A6A6ED  swan_initialize_          332  swanmain.f90
coawstM            0000000000A0A136  waves_control_mod          76  waves_control.f90
coawstM            000000000041EFFD  MAIN__                    360  master.f90
coawstM            0000000000419122  Unknown               Unknown  Unknown
libc-2.17.so       00002B353AFA4495  __libc_start_main     Unknown  Unknown
coawstM            0000000000419029  Unknown               Unknown  Unknown`
The log files and the scritp.in files were attached in this post.
Please help me to resolve this issue!
Thank you very much!

[COAWST.err.txt](https://github.com/jcwarner-usgs/COAWST/files/6499028/COAWST.err.txt)
[COAWST.out.txt](https://github.com/jcwarner-usgs/COAWST/files/6499029/COAWST.out.txt)
[coupling.in.txt](https://github.com/jcwarner-usgs/COAWST/files/6499030/coupling.in.txt)
[ocean.in.txt](https://github.com/jcwarner-usgs/COAWST/files/6499031/ocean.in.txt)
[swan.in.txt](https://github.com/jcwarner-usgs/COAWST/files/6499032/swan.in.txt)

**Comment by jcwarner-usgs** [comment]
i see
forrtl: severe (174): SIGSEGV, segmentation fault occurred
Image              PC                Routine            Line        Source             
coawstM            0000000003C1C1DA  Unknown               Unknown  Unknown
libpthread-2.17.s  00002AE4C4B3B5D0  Unknown               Unknown  Unknown
coawstM            0000000000BD1AB4  swboun_                  3546  swanpre2.f90
coawstM            0000000000ADDE5E  swread_                  1851  swanpre1.f90

so looks like SWAN had a problem.  Were there any Err* files?  what do the PRINT* files have?

**Comment by Ntmanh18196** [comment]
Hi John,
The Err file and the PRINT file are in the below.
[Errfile01-001.txt](https://github.com/jcwarner-usgs/COAWST/files/6502199/Errfile01-001.txt)
[PRINT01-001.txt](https://github.com/jcwarner-usgs/COAWST/files/6502200/PRINT01-001.txt)

**Comment by jcwarner-usgs** [comment]
looks like 2 separate problems.

1- READGRID COORDINATES 1 'Projects/Doksuri12Z1309/swan_coord.grd' 4 0 0 FREE
 ** Error            : Unexpected end of file while reading 
This usually means that you are not listing the size of the grid correctly.
you have
CGRID CURVILINEAR 450 285 EXC 9.999000e+003 9.999000e+003 CIRCLE 36 0.04 1.0 24

so if you look at the size of the roms grid, it should be
size(h)=451 286
Swan needs one less in each direction.

2- BOUNDSPEC SEGMENT XY 91.6313 -11.9268 91.6313 -8.6508 VARIABLE FILE 0 'Projects/Doksuri12Z1309/TPAR1.txt'
 ** Error            : invalid boundary point
 segment point      91.63     -8.65 grid   432.00   18.01 433  19
so you are putting information on the swan boundary, but that point is outside the domain or it is listed incorrectly.
please look at the swan user manual to see how to list these points.

-j

**Comment by Ntmanh18196** [comment]
Hi John,
I've changed my grid point of SWAN model, but it still failed. I attached my err files in the below.
Can you kindly help me to find out the problem?
Thank you very much!
[Err.zip](https://github.com/jcwarner-usgs/COAWST/files/6507128/Err.zip)

**Comment by jcwarner-usgs** [comment]
in the PRINT-001 file it has:

   
 BOUNDSPEC SEGMENT XY 91.6313 20.8134 91.6313 23.8928 VARIABLE FILE 0 'Projects/Doksuri12Z1309/TPAR11.txt'
 point with location      91.6313     23.8928 is not active
 ** Error            : invalid boundary point
 segment point      91.63     23.89 grid   -99.00  -99.00 -98 -98
 ** Error            : (  -99  -99) is outside computational grid                                      
    

So it looks like there might be an issue with the location of the TPAR11 file. 
For now you can just comment that line and see if it runs. then go back and adjust the location of that point.
& BOUNDSPEC SEGMENT XY 91.6313 20.8134 91.6313 23.8928 VARIABLE FILE 0 'Projects/Doksuri12Z1309/TPAR11.txt'

**Comment by Ntmanh18196** [comment]
Hi John,
After I changed the line in the TPAR data of the swan.in file, the error related to the TPAR data didn't occur again.
But model had the warning that made it not to work:
 &COMPUTE STAT 20170913.500000
 COMPUTE NONSTAT 20170913.500000 6 HR 20170915.500000
 ** Warning          : Quadruplets will be updated per iteration
 ** Warning          : instead of per sweep. This will increase
 ** Warning          : amount of internal memory with a factor 2
 Please help me resolve this problem!
Thank you very much.

**Comment by jcwarner-usgs** [comment]
this is just a Warning, and should not have stopped the program.
if it is not running, there is a problem somewhere else.
look for any Err files, look in the PRINT files, look at any other output files.

**Comment by jcwarner-usgs** [comment]
the .err file shows
MCT::m_SparseMatrixPlus::initFromRoot_:: FATAL--length of vector y different from row count of sMat.Length of y =   128250 Number of rows in sMat =   127516
so there is an issue with the scrip interpolation weights, possibly.
when you made the weights file, can you post the scrip.in?

**Comment by Ntmanh18196** [comment]
Hi John,
My ROMS grid has 450:285 prid points:
` netcdf_load('ROMS_COAWST_grd1.nc')
 size(h)
ans =
   450   285`
And the of ROMS grid is declared in the ocean.in file like that:
          Lm == 448           ! Number of I-direction INTERIOR RHO-points -2
          Mm == 283           ! Number of J-direction INTERIOR RHO-points -2
the size of SWAN model is 1 less than the number of ROMS model, so I set up it with 449:284 points.
[ocean.in.txt](https://github.com/jcwarner-usgs/COAWST/files/6516293/ocean.in.txt)
[scrip_coawst_dokduri.in.txt](https://github.com/jcwarner-usgs/COAWST/files/6516294/scrip_coawst_dokduri.in.txt)
[swan.in.txt](https://github.com/jcwarner-usgs/COAWST/files/6516296/swan.in.txt)

**Comment by Ntmanh18196** [comment]
Hi John,
Do you have a time to help me find out the error in this case?

**Comment by jcwarner-usgs** [comment]
this should be:

SWAN_COORD(1)='../../Projects/Doksuri12Z1309/swan_coord.grd',
SWAN_BATH(1)='../../Projects/Doksuri12Z1309/swan_bathy.bot',
SWAN_NUMX(1)=450,
SWAN_NUMY(1)=285,
CARTESIAN(1)=0,
can u try that, recreate SCRIP weights file?

**Comment by Ntmanh18196** [comment]
Hi John,
I've changed my script file according to your suggestion, however it still failed.
Can you kindly help me to resolve this problem.
[COAWST.out.txt](https://github.com/jcwarner-usgs/COAWST/files/6524330/COAWST.out.txt)

[COAWST.err.txt](https://github.com/jcwarner-usgs/COAWST/files/6524329/COAWST.err.txt)

**Comment by jcwarner-usgs** [comment]
so this is a new error.  you are making progress.

I see
"forrtl: severe (174): SIGSEGV, segmentation fault occurred
Image              PC                Routine            Line        Source             
coawstM            0000000003C1C1DA  Unknown               Unknown  Unknown
libpthread-2.17.s  00002B21958645D0  Unknown               Unknown  Unknown
coawstM            0000000000BD1AB4  swboun_                  3546  swanpre2.f90
coawstM            0000000000ADDE5E  swread_                  1851  swanpre1.f90
coawstM            0000000000A6A6ED  swan_initialize_          332  swanmain.f90
coawstM            0000000000A0A136  waves_control_mod          76  waves_control.f90
coawstM            000000000041EFFD  MAIN__                    360  master.f90"

this has something to do with SWAN reading the boundary data. 
Do all those TPAR files exist?  do they all have data in them?  did you get any Err* files?

**Comment by Ntmanh18196** [comment]
Hi John,
I've tried changing the number of grid points of SWAN on swan.in is less 1 than the figure of ROMS model and this figure on script.in is more 1 than that of swan.in. Finally, it worked.
Thank you for your help!

**Comment by jcwarner-usgs** [comment]
glad it worked.
-j
