### ISSUE TITLE
How to download the real time wave data 

### ISSUE THREAD

**Issue by Ntmanh18196** [DOI-USGS/COAWST#39]
Hi John,
Can you kindly give me a sample program to download the real time wave data?
I've tried many methods on the internet but I got only html of the website.
Thank you very much!

**Comment by jcwarner-usgs** [comment]
%this url will change every day
url='http://nomads.ncep.noaa.gov:80/dods/wave/gfswave/20210521/gfswave.global.0p25_00z';
time=ncread(url,'time');
%pick a time index
tidx=1;
hwave=ncread(url,'htsgwsfc',[1 1 tidx],[Inf Inf 1]);
lon=ncread(url,'lon');
lat=ncread(url,'lat');
figure
pcolor(lon,lat,hwave')
shading flat

![image](https://user-images.githubusercontent.com/11789880/119142291-50a47700-ba14-11eb-81a7-3a1c47874a72.png)

**Comment by Ntmanh18196** [comment]
Hi John,
Thank you very much for your help.
I used your code and tested in my matlab. Luckily, it worked.
The next step is that this data is interpolated into the grid to create the TPAR files. So can you help me some basic step to do this with one variable. Then I will practice with others variables.
I've tried modifying the create_TPAR script, but it still stucked.
Thank you very much!

**Comment by jcwarner-usgs** [comment]
the readww3_2TPAR m file has the interpolation:

  FCr = griddedInterpolant(daplon,fliplr(daplat),fliplr(hs),method);
  HS(:,tidx)=FCr(gx,gy);

where daplon daplat are the lon lat from WW3, hs is read from the thredds server,
and gx,gy are the points to interpolate to. You could use the whole grid for gx,gy.
-j

**Comment by Ntmanh18196** [comment]
Hi John,
I've tried modifying the readww3_2TPAR.m script to download and interpolate the data into my grid, however I got the error:
`>> test_2105
NCTOOLBOX added to Matlab path
working_dir =    'E:\Matlab_ud06h'
We are adding 0 to the roms longitude - line 34 ww3gb_2TPAR.m
getting hs tp and dp for 20200524.1200
Error using griddedInterpolant
The grid must be created from grid vectors which are strictly monotonically increasing.
Error in readww3_2TPAR (line 65)
  FCr = griddedInterpolant(daplon,fliplr(daplat),fliplr(hs),method);
Error in test_2105 (line 41)
readww3_2TPAR(modelgrid,yearww3,mmww3,ddww3,specpts)`
Please help me to resolve this problem!
I also attach my script in the below.
Thank you very much!
[readww3_2TPAR.m.txt](https://github.com/jcwarner-usgs/COAWST/files/6538369/readww3_2TPAR.m.txt)

**Comment by Ntmanh18196** [comment]
Hi John,
Can you kindly help me to resolve this error?
Thank you very much!

**Comment by jcwarner-usgs** [comment]
Error using griddedInterpolant The grid must be created from grid vectors which are strictly monotonically increasing.
this is telling you that your grid needs to be continuously increasing.  so it can not be
[0 1 3 2 4 ...] 
it would have to be
[0 1 2 3 4 ...
somewhere your grid is not continuously increasing.

**Comment by Ntmanh18196** [comment]
Hi John,
I'm trying to practice with another day, but I got the other error:
`We are adding 0 to the roms longitude - line 34 ww3gb_2TPAR.m
Error using quit
Too many output arguments.
Error in readww3_2TPAR2 (line 39)
daplon=lonww3(ig0:ig1,jg0:jg1); daplat=quit(ig0:ig1,jg0:jg1);
Error in test_2105 (line 41)
readww3_2TPAR2(modelgrid,yearww3,mmww3,ddww3,specpt`

I also attach my script in the below.
Please help me to address it!
[readww3_2TPAR2.m.txt](https://github.com/jcwarner-usgs/COAWST/files/6576875/readww3_2TPAR2.m.txt)

**Comment by Ntmanh18196** [comment]
Hi John,
I did debug the former error.
Regarding your explanation, my grid needs to be continuously increasing. so somewhere in my grid is not continuously increasing.
How can I do to examine my grid?
By the way, I practiced the similar grid with ww3_grid data and the error didn't appear.

**Comment by Ntmanh18196** [comment]
Hi John,
I've modified the code and I can download the data but the line is displayed the data in 2020. And it failed at writing the Bound_spec file.

 run Sample.m
NCTOOLBOX added to Matlab path
url =   'http://nomads.ncep.noaa.gov:80/dods/wave/gfswave/20210601/gfswave.global.0p25_00z'
We are adding 0 to the roms longitude - line 34 ww3gb_2TPAR.m
getting hs tp and dp for 20200601.0000
getting hs tp and dp for 20200601.0300
getting hs tp and dp for 20200601.0600
getting hs tp and dp for 20200601.0900
getting hs tp and dp for 20200601.1200
getting hs tp and dp for 20200601.1500
getting hs tp and dp for 20200601.1800
getting hs tp and dp for 20200601.2100
getting hs tp and dp for 20200602.0000
getting hs tp and dp for 20200602.0300
getting hs tp and dp for 20200602.0600
getting hs tp and dp for 20200602.0900
getting hs tp and dp for 20200602.1200
getting hs tp and dp for 20200602.1500
getting hs tp and dp for 20200602.1800
getting hs tp and dp for 20200602.2100
getting hs tp and dp for 20200603.0000
getting hs tp and dp for 20200603.0300
getting hs tp and dp for 20200603.0600
getting hs tp and dp for 20200603.0900
getting hs tp and dp for 20200603.1200
getting hs tp and dp for 20200603.1500
getting hs tp and dp for 20200603.1800
getting hs tp and dp for 20200603.2100
getting hs tp and dp for 20200604.0000
getting hs tp and dp for 20200604.0300
getting hs tp and dp for 20200604.0600
getting hs tp and dp for 20200604.0900
getting hs tp and dp for 20200604.1200
getting hs tp and dp for 20200604.1500
getting hs tp and dp for 20200604.1800
getting hs tp and dp for 20200604.2100
getting hs tp and dp for 20200605.0000
getting hs tp and dp for 20200605.0300
getting hs tp and dp for 20200605.0600
getting hs tp and dp for 20200605.0900
getting hs tp and dp for 20200605.1200
getting hs tp and dp for 20200605.1500
getting hs tp and dp for 20200605.1800
getting hs tp and dp for 20200605.2100
getting hs tp and dp for 20200606.0000
getting hs tp and dp for 20200606.0300
getting hs tp and dp for 20200606.0600
getting hs tp and dp for 20200606.0900
getting hs tp and dp for 20200606.1200
getting hs tp and dp for 20200606.1500
getting hs tp and dp for 20200606.1800
getting hs tp and dp for 20200606.2100
getting hs tp and dp for 20200607.0000
getting hs tp and dp for 20200607.0300
getting hs tp and dp for 20200607.0600
getting hs tp and dp for 20200607.0900
getting hs tp and dp for 20200607.1200
getting hs tp and dp for 20200607.1500
getting hs tp and dp for 20200607.1800
getting hs tp and dp for 20200607.2100
getting hs tp and dp for 20200608.0000
getting hs tp and dp for 20200608.0300
getting hs tp and dp for 20200608.0600
getting hs tp and dp for 20200608.0900
getting hs tp and dp for 20200608.1200
getting hs tp and dp for 20200608.1500
getting hs tp and dp for 20200608.1800
getting hs tp and dp for 20200608.2100
getting hs tp and dp for 20200609.0000
getting hs tp and dp for 20200609.0300
getting hs tp and dp for 20200609.0600
getting hs tp and dp for 20200609.0900
getting hs tp and dp for 20200609.1200
getting hs tp and dp for 20200609.1500
getting hs tp and dp for 20200609.1800
getting hs tp and dp for 20200609.2100
getting hs tp and dp for 20200610.0000
getting hs tp and dp for 20200610.0300
getting hs tp and dp for 20200610.0600
getting hs tp and dp for 20200610.0900
getting hs tp and dp for 20200610.1200
getting hs tp and dp for 20200610.1500
getting hs tp and dp for 20200610.1800
getting hs tp and dp for 20200610.2100
getting hs tp and dp for 20200611.0000
getting hs tp and dp for 20200611.0300
getting hs tp and dp for 20200611.0600
getting hs tp and dp for 20200611.0900
getting hs tp and dp for 20200611.1200
getting hs tp and dp for 20200611.1500
getting hs tp and dp for 20200611.1800
getting hs tp and dp for 20200611.2100
getting hs tp and dp for 20200612.0000
getting hs tp and dp for 20200612.0300
getting hs tp and dp for 20200612.0600
getting hs tp and dp for 20200612.0900
getting hs tp and dp for 20200612.1200
getting hs tp and dp for 20200612.1500
getting hs tp and dp for 20200612.1800
getting hs tp and dp for 20200612.2100
getting hs tp and dp for 20200613.0000
getting hs tp and dp for 20200613.0300
getting hs tp and dp for 20200613.0600
getting hs tp and dp for 20200613.0900
getting hs tp and dp for 20200613.1200
getting hs tp and dp for 20200613.1500
getting hs tp and dp for 20200613.1800
getting hs tp and dp for 20200613.2100
getting hs tp and dp for 20200614.0000
getting hs tp and dp for 20200614.0300
getting hs tp and dp for 20200614.0600
getting hs tp and dp for 20200614.0900
getting hs tp and dp for 20200614.1200
getting hs tp and dp for 20200614.1500
getting hs tp and dp for 20200614.1800
getting hs tp and dp for 20200614.2100
getting hs tp and dp for 20200615.0000
getting hs tp and dp for 20200615.0300
getting hs tp and dp for 20200615.0600
getting hs tp and dp for 20200615.0900
getting hs tp and dp for 20200615.1200
getting hs tp and dp for 20200615.1500
getting hs tp and dp for 20200615.1800
getting hs tp and dp for 20200615.2100
getting hs tp and dp for 20200616.0000
getting hs tp and dp for 20200616.0300
getting hs tp and dp for 20200616.0600
getting hs tp and dp for 20200616.0900
getting hs tp and dp for 20200616.1200
getting hs tp and dp for 20200616.1500
getting hs tp and dp for 20200616.1800
getting hs tp and dp for 20200616.2100
getting hs tp and dp for 20200617.0000
writing out file TPAR1
writing out file TPAR2
writing out file TPAR3
writing out file TPAR4
writing out file TPAR5
writing out file TPAR6
writing out file TPAR7
writing out file TPAR8
writing out file TPAR9
writing out file TPAR10
writing out file TPAR11
writing out file TPAR12
writing out file TPAR13
writing out file TPAR14
writing out file TPAR15
writing out file TPAR16
writing out file TPAR17
writing out file TPAR18
writing out file TPAR19
Attempt to execute SCRIPT bdry_com as a function:
/work/users/cloud/user/manh/COAWST/Daily_run/bdry_com.m
Error in Sample (line 51)
bdry_com(specpts) %script writes out file Bound_spec_command to working directory

Can you kindly have me some advices?

[readww3_2TPAR2.m.txt](https://github.com/jcwarner-usgs/COAWST/files/6603852/readww3_2TPAR2.m.txt)
[Sample.m.txt](https://github.com/jcwarner-usgs/COAWST/files/6603853/Sample.m.txt)
