### ISSUE TITLE
MPI error in executing coawstM

### ISSUE THREAD

**Issue by jhmoon9329** [DOI-USGS/COAWST#41]
Hi, John.
I am a beginner at COAWST, and I have a problem in executing the coawstM. 
I'm trying to run WRF-ROMS coupled model to simulate the tropical cyclone.
I succeeded to compile coawstM, but there was a fatal error when I submit the job.
the error message is shown below,

[cli_13]: aborting job:
Fatal error in PMPI_Cart_create:
Invalid communicator, error stack:
PMPI_Cart_create(318): MPI_Cart_create(comm=0xffff8002, ndims=2, dims=0x3d18ba8, periods=0x8ef9bf0, reorder=0, comm_cart=0x7ffff93b29ac) failed
PMPI_Cart_create(256): Invalid communicator

I uploaded my compile script, run scripts, and log files.
Are there any mistakes in compiling or namelists?

[coawst.bash.txt](https://github.com/jcwarner-usgs/COAWST/files/6532710/coawst.bash.txt)
[coupling_wrftc.in.txt](https://github.com/jcwarner-usgs/COAWST/files/6532712/coupling_wrftc.in.txt)
[namelist.input.txt](https://github.com/jcwarner-usgs/COAWST/files/6532713/namelist.input.txt)
[ocean_wrftc.in.txt](https://github.com/jcwarner-usgs/COAWST/files/6532714/ocean_wrftc.in.txt)
[run_wrftc.out.txt](https://github.com/jcwarner-usgs/COAWST/files/6532715/run_wrftc.out.txt)
[wrftc.h.txt](https://github.com/jcwarner-usgs/COAWST/files/6532716/wrftc.h.txt)
[WRFTC.o3576.txt](https://github.com/jcwarner-usgs/COAWST/files/6532717/WRFTC.o3576.txt)

**Comment by jcwarner-usgs** [comment]
i can look at this more later, but maybe you need to set nproc_x and nproc_y in the namelist.input (see the Sandy case as an example).

**Comment by jcwarner-usgs** [comment]
did you compile WRF with parallel IO?? that is also sometimes an issue.

**Comment by jhmoon9329** [comment]
Thank you for your response.
I added 'nproc_x = 4, nproc_y = 3' to the namelist, but same error.
I compiled the WRF with parallel (dmpar)

**Comment by jcwarner-usgs** [comment]
i intend to make the MCT flags to be automatic, but in the meantime try this (oc2at needs to be on)

#define ROMS_MODEL
#define NESTING
#define WRF_MODEL
#undef SWAN_MODEL
#undef  WW3_MODEL
#define MCT_LIB
#define MCT_INTERP_OC2AT
#undef MCT_INTERP_WV2AT
#undef MCT_INTERP_OC2WV

**Comment by jhmoon9329** [comment]
I recompiled with 'define MCT_INTERP_OC2AT', but the same error.

I found that the same error occurred when I execute the real.exe compiled by coawst.bash
but, when I compile only WRF model in COAWST folder, the real.exe work normally.

**Comment by jcwarner-usgs** [comment]
ok, you need to take the steps here one at a time. follow the steps in the manual.
first compile WRF, and do all the WPS and real preprocessing steps.  then run WRF by itself to make sure it works.
then compile WRF+ROMS, and run that together.
can you try this step by step?

**Comment by jhmoon9329** [comment]
I tried to compile the COAWST on another server with an intel compiler, and it works.
I think the first server that I tried is not compatible with COAWST.
Now, WRF-ROMS coupled model to simulate TC is running well. 
Thank you for your reply.
