### ISSUE TITLE
ROMS dogbone composite nesting problem

### ISSUE THREAD

**Issue by UMZhilongLiu** [DOI-USGS/COAWST#42]
Hi,

We are trying to utilize the composite grid in ROMS 3.9. Initially, we tested the dogbone case, which is attached in ROMS 3.9 tutorials but not in COAWST. It seems that there is a bug in the code. Someone has posted it in the ROMS Forum. https://www.myroms.org/forum/viewtopic.php?t=5773. We are having the same problem and are looking forward to hearing updates of that. 

Thanks,
Zhilong

**Comment by jcwarner-usgs** [comment]
i found the problem, and working with Hernan to fix it.  keep checking that post for updates.
-j



John C. Warner, Ph.D.
U.S. Geological Survey
384 Woods Hole Road
Woods Hole, MA 02543
508-457-2237<tel:508-457-2237> ph. 508-457-2310<tel:508-457-2310> fax
***@***.******@***.***>

https://www.usgs.gov/staff-profiles/john-warner


________________________________
From: UMZhilongLiu ***@***.***>
Sent: Monday, May 24, 2021 1:21 PM
To: jcwarner-usgs/COAWST ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [EXTERNAL] [jcwarner-usgs/COAWST] ROMS dogbone composite nesting problem (#42)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



Hi,

We are trying to utilize the nested grid in ROMS 3.9. Initially, we tested the dogbone case, which is attached in ROMS 3.9 tutorials but not in COAWST. It seems that there is a bug in the code. Someone has posted it in the ROMS Forum. https://www.myroms.org/forum/viewtopic.php?t=5773<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.myroms.org%2Fforum%2Fviewtopic.php%3Ft%3D5773&data=04%7C01%7Cjcwarner%40usgs.gov%7C9a220e48b0fd4444f48c08d91ed874fb%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637574737294584978%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=qknXfjj03G3eU4AikAlIzS5lujPxHflrKbc8e8WUOBY%3D&reserved=0>. We are having the same problem and are looking forward to hearing updates of that.

Thanks,
Zhilong

**Comment by UMZhilongLiu** [comment]
Thank you very much! Really appreciate it!

**Comment by jcwarner-usgs** [comment]
glad it works now.
