### ISSUE TITLE
WRF Calculation error

### ISSUE THREAD

**Issue by MartaGoncalves** [DOI-USGS/COAWST#43]
Hello,

I'm leaving here may .log in order to see if you can help me.
thank you in advance
Marta

Ps I belive I have a Netcdf error to

[build.log](https://github.com/jcwarner-usgs/COAWST/files/6534449/build.log)

**Comment by jcwarner-usgs** [comment]
ok, the build says "Will use NETCDF in dir: /home/marta/MODELS/COAWST/LIB/netcdf4/include"
so lets try a few things. 
cd to  /home/marta/MODELS/COAWST/LIB/netcdf4/bin
and type
./nc-config --all
that way we are running nc-config on your install.  post the output here.
It should say     --has-nc4 -> yes

If it says --has-nc4 -> no, then try to recompile netcdf with nc4 enabled.

if it says --has-nc4 -> yes, then i am not sure what is wrong with your install, so then lets try to use the NETCDF from the main cluster admin people.  Not sure what that path would be, but do
export NETCDF=/path_to_main_admin_netcdf
and then
./coawst.bash -j 4

**Comment by MartaGoncalves** [comment]
Dear John,

Thank you for your response.

I changed the some of my paths and re-run coaswt.bash.
I'm finally having some results.

however when run the coaswt.bash I was expecting to have an "executables successfully built" or something close, but the .log doesn't show anything.

I tryed to run testcase Sandy and I have some results, but i'm not confident with them.

thanks in advance,

Marta 
[build3.log](https://github.com/jcwarner-usgs/COAWST/files/6541704/build3.log)

**Comment by MartaGoncalves** [comment]
Dear John,

Thank you for your response.

I changed the some of my paths and re-run coaswt.bash.
I'm finally having some results.

however when run the coaswt.bash I was expecting to have an "executables successfully built" or something close, but the .log doesn't show anything.

I tryed to run testcase Sandy and I have some results, but i'm not confident with them.

thanks in advance,

Marta 
[build.log](https://github.com/jcwarner-usgs/COAWST/files/6541884/build.log)

**Comment by jcwarner-usgs** [comment]
So i do see this a few times:

"/usr/bin/ld: /home/marta/MODELS/COAWST/LIB/netcdf4/lib/libnetcdff.so: undefined reference to `nc_set_var_chunk_cache_ints'
/usr/bin/ld: /home/marta/MODELS/COAWST/LIB/netcdf4/lib/libnetcdff.so: undefined reference to `nc_def_var_chunking_ints'
collect2: error: ld returned 1 exit status
Command exited with non-zero status 1"

that means there is an undefined nc_ variable in your libnetdff.so 
This issue has been seen before

https://www.unidata.ucar.edu/support/help/MailArchives/netcdf/msg14662.html

A fix may be to change the order of the libs from
-L/home/marta/MODELS/COAWST/LIB/netcdf4/lib -lnetcdff -lnetcdf   
to
-L/home/marta/MODELS/COAWST/LIB/netcdf4/lib -lnetcdf -lnetcdff   

I think that would be in the WRF/configure.defaults.
but if you got a coawstM, then is should work.
do you want to paste a jpg image of the wrfout output? you should see similar results as i showed on monday.

**Comment by MartaGoncalves** [comment]
Dear John
Thank you for your help.
I'm attaching my output results, they seem  similar to the results you showed.

I'm going to make the changes in the Netcdf compilation and I'll let you know if it worked.

once again thank you
Marta
![SST](https://user-images.githubusercontent.com/84739587/119649366-749ff800-be1a-11eb-87ed-bf567929cdcc.jpg)
![Imagem1](https://user-images.githubusercontent.com/84739587/119649368-75388e80-be1a-11eb-8605-2b31dbbcf0f8.jpg)
![PSFC](https://user-images.githubusercontent.com/84739587/119649377-77025200-be1a-11eb-8fd8-fc3a20c0d8ec.jpg)
