### ISSUE TITLE
compiling sandy test case for the 1st time

### ISSUE THREAD

**Issue by nvc21** [DOI-USGS/COAWST#44]
Hi there
I'm trying to compile the sandy test case for the 1st time. I've already managed to compile and run the rip_current case and everything went smoothly. I'm attaching the output to
./coawst.bash -j 12 >> output.txt
[output.txt](https://github.com/jcwarner-usgs/COAWST/files/6549145/output.txt)
Anybody could give me some tips?

**Comment by tarankalra1** [comment]
The first error that i see is that the compiler can't find netcdf.inc 


Error : Not found /sw/apps/suse/intel17/netcdf/4.5.0/include/include/netcdf.inc
        Please check this installation of NetCDF and re-run this configure script

**Comment by jcwarner-usgs** [comment]
yes, WRF needs an environmental variable called NETCDF
export NETCDF=/path_to_your_netcdf

ROMS needs NETCDF_INCDIR and NETCDF_LIBDIR , which it sounds like you have set already.
so just set the netcdf path and see if that works.
