### ISSUE TITLE
error compiling WW3

### ISSUE THREAD

**Issue by carolina-bernardo** [DOI-USGS/COAWST#45]
Hi! I am trying to compile WW3 using the coawst.bash and running Sandy test case with WW3 only, but i keep geting an error (..../comp.gfortran not found). I managed to run coawst.bash and compile WRF, ROMS and SWAN, also for sandy test case with no problems, but cant make i t run with WW3 only options. I have attached the log file.
[build.log](https://github.com/jcwarner-usgs/COAWST/files/6553578/build.log)
 May be someone knows how to fix this issue, 
Thank you, 
Carolina

**Comment by jcwarner-usgs** [comment]
yes i have seen this before. there are some changes to the way WW3 builds. maybe we could share screen at some time after the meeting.  I think i want you to make a change in cmplr.env, it does not see 'gfortran' it is looking for gnu.  but there might be one more catch somewhere. 
how good are you at trying things?
can you change line 208 in WW#/model/bin/cmplr.env from
if [ "$cmplr" == "gnu" ] || [ "$cmplr" == "gnu_debug" ] || [ "$cmplr" == "gnu_prof" ] || \
to
if [ "$cmplr" == "gnu" ] || [ "$cmplr" == "gnu_debug" ] || [ "$cmplr" == "gnu_prof" ] || [ "$cmplr" == "gfortran" ] ||\

-j

**Comment by carolina-bernardo** [comment]
Hi,  
I tried the modifications of line 208 as you suggested but it didn't solve it. I send the new log attached. 
I am using WRF already for a few years, and have experience with its compilation in particular. But definitely don't have a solid
understanding of this matters in general. So I would appreciate your 
[build.log](https://github.com/jcwarner-usgs/COAWST/files/6554565/build.log)
help to solve it, sharing the screen is a good idea.  
Thank you !

**Comment by jcwarner-usgs** [comment]
can you do an update and try again?
i think it should be fixed now.
-j
