### ISSUE TITLE
Issue with ./coawst.bash

### ISSUE THREAD

**Issue by sarasari206** [DOI-USGS/COAWST#49]
Hi, 
After I try this command in installing COAWST : ./coawst.bash

I get this error:
ifort: warning #10193: -vec is default; use -x and -ax to configure vectorization
distribute.f90(3711): error #7013: This module file was not generated by any release of this                                 compiler.   [NETCDF]
      USE netcdf
----------^
distribute.f90(4139): error #7013: This module file was not generated by any release of this                                 compiler.   [NETCDF]
      USE netcdf
----------^
distribute.f90(3752): error #6404: This name does not have a type, and must have an explicit                                 type.   [NF90_NOERR]
      mp_ncread1d=nf90_noerr
------------------^
distribute.f90(3766): error #6404: This name does not have a type, and must have an explicit                                 type.   [EXIT_FLAG]
        exit_flag=2
--------^
distribute.f90(3805): error #6404: This name does not have a type, and must have an explicit                                 type.   [NF90_INQ_VARID]
        mp_ncread1d=nf90_inq_varid(ncid, TRIM(ncvname), varid)
--------------------^
distribute.f90(3811): error #6404: This name does not have a type, and must have an explicit                                 type.   [NOERROR]
        IF (exit_flag.eq.NoError) THEN
-------------------------^
distribute.f90(3815): error #6404: This name does not have a type, and must have an explicit                                 type.   [NF90_GET_VAR]
            mp_ncread1d=nf90_get_var(ncid, varid,  Asend, start, total)
------------------------^
distribute.f90(4020): error #6404: This name does not have a type, and must have an explicit                                 type.   [NF90_INQ_VARID]
        mp_ncread2d=nf90_inq_varid(ncid, TRIM(ncvname), varid)
--------------------^
distribute.f90(4032): error #6404: This name does not have a type, and must have an explicit                                 type.   [NF90_GET_VAR]
            mp_ncread2d=nf90_get_var(ncid, varid,  Asend, start, total)
------------------------^
distribute.f90(4218): error #6404: This name does not have a type, and must have an explicit                                 type.   [NF90_INQ_VARID]
        mp_ncwrite1d=nf90_inq_varid(ncid, TRIM(ncvname), varid)
---------------------^
distribute.f90(4220): error #6404: This name does not have a type, and must have an explicit                                 type.   [NF90_PUT_VAR]
          mp_ncwrite1d=nf90_put_var(ncid, varid, Arecv, start, total)
-----------------------^
distribute.f90(4441): error #6404: This name does not have a type, and must have an explicit                                 type.   [NF90_INQ_VARID]
        mp_ncwrite2d=nf90_inq_varid(ncid, TRIM(ncvname), varid)
---------------------^
distribute.f90(4443): error #6404: This name does not have a type, and must have an explicit                                 type.   [NF90_PUT_VAR]
          mp_ncwrite2d=nf90_put_var(ncid, varid, Arecv, start, total)
-----------------------^
compilation aborted for distribute.f90 (code 1)
make: *** [ROMS/Utility/Module.mk:15: Build/distribute.o] Error 1

Please let me know how I can fix it?
Thank you, 
Sara

**Comment by jcwarner-usgs** [comment]
looks like the Netcdf libraries that you are linking to were built by a different compiler. So for example, if you are using ifort then maybe those netcdf libs were built by gfortran, or something like that.
Can you find out who build those netcdf libs and what they used?

**Comment by sarasari206** [comment]
Hi John, 
Thanks for your response. I was waiting for an answer from them but it seems that it will be slow.
Is there any way that I can check this by myself? As, I was not sure about the type of their compilers I installed my own ones in a directory and asked COAWST to read it from there. I think that's why I got this error.
Thank you, 
Soudeh

**Comment by jcwarner-usgs** [comment]
you could try:
nf-config --all

for me it returns:


This netCDF-Fortran 4.4.4 has been built with the following features:

  --cc        -> mpiicc
  --cflags    ->  -I/vortexfs1/apps/impistack-1.0/include -I/vortexfs1/apps/impistack-1.0/include

  --fc        -> mpiifort
  --fflags    -> -I/vortexfs1/apps/impistack-1.0/include
  --flibs     -> -L/vortexfs1/apps/impistack-1.0/lib -lnetcdff -L/vortexfs1/apps/impistack-1.0/lib -lnetcdf -lnetcdf
  --has-f90   -> no
  --has-f03   -> yes

  --has-nc2   -> yes
  --has-nc4   -> yes

  --prefix    -> /vortexfs1/apps/impistack-1.0
  --includedir-> /vortexfs1/apps/impistack-1.0/include
  --version   -> netCDF-Fortran 4.4.4

**Comment by occsail** [comment]
Hi John,
I am trying to install COAWST : ./coawst.bash but I get stuck in the ROMS module with error:

gfortran: error: unrecognized command line option ‘-fallow-argument-mismatch’; did you mean ‘-Wno-argument-mismatch’?
make: *** [ROMS/Modules/Module.mk:15: Build/mod_kinds.o] Error 1
make: *** Waiting for unfinished jobs....
gfortran: error: unrecognized command line option ‘-fallow-argument-mismatch’; did you mean ‘-Wno-argument-mismatch’?
make: *** [ROMS/Modules/Module.mk:15: Build/mod_strings.o] Error 1

[build.log](https://github.com/jcwarner-usgs/COAWST/files/8831470/build.log)
Can you help please.

**Comment by jcwarner-usgs** [comment]
i do not see that error in the build.log, but maybe it went to screen and not to the log.
that is strange because the -allow argument mismatch is a gfortran flag.  maybe you have an old compiler.
try this.
I think you are using Linux, with gfortan so edit
Compilers/Linux-gfortran.mk
and search for the "mismatch" flag
probalby looks like this
           FFLAGS := -frepack-arrays -fallow-argument-mismatch
make a copy of that line and comment it out so that you know what it looked like, then remove that flag
so now you have 2 lines:

#          FFLAGS := -frepack-arrays -fallow-argument-mismatch
           FFLAGS := -frepack-arrays
the # makes that line a comment.
then do a new build.  try
./coawst.bash -noclean -nocleanwrf
if that does not work then do a full build
./coawst.bash

let me know if that works

-j

**Comment by occsail** [comment]
It continued for a bit, John.  It then stopped with:

get_sparse_matrix.f90:71:15:

   71 |         status=nf90_inq_ncid(ncSPSid,grp_name,grpid)
        |               1
Error: Function ‘nf90_inq_ncid’ at (1) has no IMPLICIT type; did you mean ‘nf90_inq_dimid’?
make: *** [Master/Module.mk:25: Build/get_sparse_matrix.o] Error 1
make: *** Waiting for unfinished jobs....
[coawst.log](https://github.com/jcwarner-usgs/COAWST/files/8832683/coawst.log)

**Comment by jcwarner-usgs** [comment]
can you type:
nf-config --all

**Comment by occsail** [comment]
Hi John,  

Success!  I tried it first using library versions mentioned in "https://www2.mmm.ucar.edu/wrf/OnLineTutorial/compilation_tutorial.php"  but it worked when I used newer versions (hdf5-1.12.2.tar.gz, zlib-1.2.12.tar.gz, libpng-1.6.37.tar.gz, netcdf-c-4.8.1.tar.gz, netcdf-fortran-4.5.3.tar.gz, netcdf-cxx-4.2.tar.gz, jasper-2.0.14.tar.gz, mpich-3.4.tar.gz).  Still needed the "FFLAGS := -frepack-arrays" modification you suggested.

Thanks so much!
[ncconfig.txt](https://github.com/jcwarner-usgs/COAWST/files/8837216/ncconfig.txt)

**Comment by venuscheung** [comment]
Hi John, I have a similar issue on ./coaswt.bash -noclean too. 
I have attached the log file and the nf-config for my run. Thank you in advance. 


This netCDF-Fortran 4.4.4 has been built with the following features:

  --cc        -> gcc
  --cflags    ->  -I/usr/include -Wdate-time -D_FORTIFY_SOURCE=2

  --fc        -> gfortran
  --fflags    -> -I/usr/include
  --flibs     -> -L/usr/lib -lnetcdff -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,now -lnetcdf -lnetcdf
  --has-f90   -> no
  --has-f03   -> yes

  --has-nc2   -> yes
  --has-nc4   -> yes

  --prefix    -> /usr
  --includedir-> /usr/include
  --version   -> netCDF-Fortran 4.4.4
[coawst.txt](https://github.com/jcwarner-usgs/COAWST/files/8859787/coawst.txt)

**Comment by jcwarner-usgs** [comment]
so this is a completely different error

wec_vf.f90:89:59:
      &                            FORCES(ng) % Dissip_break,            &
                                                           1
Error: ‘dissip_break’ at (1) is not a member of the ‘t_forces’ structure

there is some mismatch in the cpp settings.
send me the *.h file.  is this a distributed Project or one of your own?
and try
coawst.bash 
(without the noclean)

**Comment by venuscheung** [comment]
[question.zip](https://github.com/jcwarner-usgs/COAWST/files/8861850/question.zip)
These are the .h file in the Project, they are all come from the Project/Inlet_test/Refined, I did not modified any h file. Thank you.

**Comment by venuscheung** [comment]
I have also attached the ~/COAWST/ROMS/Nonlinear/Wec/Module.mk and wec_vf.f90 files, hope they can help in investigating the problem. Thank you. 
[wec_vf.txt](https://github.com/jcwarner-usgs/COAWST/files/8866509/wec_vf.txt)
[Module.txt](https://github.com/jcwarner-usgs/COAWST/files/8866510/Module.txt)

**Comment by jcwarner-usgs** [comment]
ok. i just downloaded a copy, and compiled the code for inlet test refined.  there were no issues.
so can you get an updated copy from here (github) and try again?
-j

**Comment by venuscheung** [comment]
The problem has solved by re-downloading the whole directory. Thank you very much!

**Comment by jcwarner-usgs** [comment]
glad you got it to work.-j
