### ISSUE TITLE
Error running sed_bed_toy and trench

### ISSUE THREAD

**Issue by galenegan** [DOI-USGS/COAWST#5]
Running the most updated version of COAWST on Ubuntu 20.04. I'm able to compile the sed_bed_toy and trench test cases producing a coawstG executable, but when I try to run it gives the following error:
```
At line 298 of file read_phypar.f90
Fortran runtime error: Index '1' of dimension 1 of array 'idtvar' above upper bound of 0
```
This occurs for both test cases (it also occurs for sed_floc_toy, but I realize that is still under development). I've attached my coawst.bash file for the sed_bed_toy case, along with log files (with debugging on) for both the compilation and run process. Any ideas about what might be going wrong are much appreciated!

Thanks,
Galen

[coawst_logs.zip](https://github.com/jcwarner-usgs/COAWST/files/4820587/coawst_logs.zip)

**Comment by tarankalra1** [comment]
Hi Galen, 

I am going to recreate this issue at my end. Is there a reason that you are running these cases in Debug mode (coawstG instead of coawstM)  ?

**Comment by galenegan** [comment]
> Hi Galen,
> 
> I am going to recreate this issue at my end. Is there a reason that you are running these cases in Debug mode (coawstG instead of coawstM) ?

Hi Taran, 

I was just about to close this actually -- figured out this morning that I was linking to the wrong .in file, and now it's running. Thank you though!

-Galen
