### ISSUE TITLE
WPS Executables in WLS linux

### ISSUE THREAD

**Issue by Glejin** [DOI-USGS/COAWST#51]
Hi ,

I successfully generated  geogrid.exe, ungrib.exe, and metgrid.exe after compiling WRF and WPS in windows subsystem for linux,  but have issue with utility executables.

I am following the instructions from COAWST_User_Manual to compile the WPS, but I could not generate the   plotfmt.exe, and plotgrid.exe utility executables. 

The executables generated after compiling are

util/g1print.exe -> ../ungrib/src/g1print.exe
util/g2print.exe -> ../ungrib/src/g2print.exe
util/rd_intermediate.exe -> src/rd_intermediate.exe
util/mod_levs.exe -> src/mod_levs.exe
util/avg_tsfc.exe -> src/avg_tsfc.exe
util/calc_ecmwf_p.exe -> src/calc_ecmwf_p.exe
util/height_ukmo.exe -> src/height_ukmo.exe
util/int2nc.exe -> src/int2nc.exe

Please let me know how I can fix it?
Thank you,

Glejin

**Comment by jcwarner-usgs** [comment]
i am not sure why those other utilities were not created. You would have to look in the output that is generated during the build to see if there are any errors listed.
if you do not need those utilities, then i suggest you just move forward.

**Comment by jcwarner-usgs** [comment]
has this issue been resolved?

**Comment by Glejin** [comment]
Yes
