### ISSUE TITLE
WRT_HIS - error

### ISSUE THREAD

**Issue by Ntmanh18196** [DOI-USGS/COAWST#54]
Hi John,
I got the error related the WRT_HIS like that:
` ** ROMS grid  1 sent data to SWAN grid  1
 == SWAN grid  1 recv data from ROMS grid  1
ROMStoSWAN Min/Max DEPTH   (m):        0.000000E+00  9.329987E+03
ROMStoSWAN Min/Max WLEV    (m):       -1.185423E+00  1.792694E+00
ROMStoSWAN Min/Max VELX    (ms-1):    -1.051749E+01  7.453914E+00
ROMStoSWAN Min/Max VELY    (ms-1):    -1.066175E+01  1.082273E+01
ROMStoSWAN Min/Max ZO      (m):        0.000000E+00  5.000000E-02
 Found Error: **   Line: 932      Source: ROMS/Utility/wrt_his.F
 WRT_HIS - error while writing variable: omega
           into history NetCDF file for time record: 2
 Found Error: 03   Line: 181      Source: ROMS/Nonlinear/output.F
 Found Error: 03   Line: 561      Source: ROMS/Nonlinear/main3d.F
 Found Error: 03   Line: 331      Source: ROMS/Drivers/nl_ocean.h, ROMS_run`
Here is my ocean namelist:
`! Time-Stepping parameters.
      NTIMES == 172800    1
          DT == 1.0d0  3.0d0
     NDTFAST == 28      28
! Output history, average, diagnostic files parameters.
     LDEFOUT == T    T
        NHIS == 3600 
     NDEFHIS == 3600 
        NQCK == 0
     NDEFQCK == 0
      NTSAVG == 1    1
        NAVG == 3600
     NDEFAVG == 3600 
      NTSDIA == 1    
        NDIA == 3600
     NDEFDIA == 3600 `
Please help me to address it!
Thank you very much.

**Comment by venuscheung** [comment]
Hi, may I know how the problem was solved as I have the exact error message. Thank you!
