### ISSUE TITLE
How to link to new files compiling Coawst

### ISSUE THREAD

**Issue by chyueouc** [DOI-USGS/COAWST#8]
Hello,

While compiling Coawst, could the new files be used in the progress? For example:
File folders Master and SWAN are copied as Master2 and SWAN2, could the new folders be used in the compilation?
Some parts were changed in makefile, like:

ifdef USE_ROMS
 modules  +=	Master2
 includes +=	Master2 Compilers
**********************
ifdef USE_SWAN
 modules  +=	SWAN2/Src
 includes +=	SWAN2/Src
endif

But it seems the compiling was still using Master and Swan, not Master2 and SWAN2.
Is there anything need to be modified except for makefile?
Thank you for your help!

Che Yue

**Comment by jcwarner-usgs** [comment]
i think it would all be in the makefile.
make sure you get all the instances of SWAN and make that SWAN2, etc.
if you send the build.out maybe i could see what is happening.
-j



John C. Warner, Ph.D.
U.S. Geological Survey
384 Woods Hole Road
Woods Hole, MA 02543
508-457-2237<tel:508-457-2237> ph. 508-457-2310<tel:508-457-2310> fax
jcwarner@usgs.gov<mailto:jcwarner@usgs.gov>

https://www.usgs.gov/staff-profiles/john-warner


________________________________

**Comment by chyueouc** [comment]
Hi Dr.Warner,
Do you mean this file?
[buildout.txt](https://github.com/jcwarner-usgs/COAWST/files/4985929/buildout.txt)
I have made all SWAN to SWANICE (only found 2 in the makefile), it was still using SWAN.
`ifdef USE_SWAN 
 modules  +=	SWANICE/Src 
 includes +=	SWANICE/Src 
endif`
Che Yue

**Comment by jcwarner-usgs** [comment]
Not sure if this is still a problem.  But i am going to close this issue.

**Comment by chyueouc** [comment]
Yes, please close this issue, my problem is solved now. Thank you for your
help, John!

Regards,
Che Yue
