### ISSUE TITLE
Error when run mpi with coawstM

### ISSUE THREAD

**Issue by Manhntvn18** [DOI-USGS/COAWST#9]
Hi all,
I run coawstM program to run the WRF model however when I submitted a job or ran with command mpirun the model system didn't work. The error was displayed below:

 `[weather@igplogin COAWST]$ mpirun -np 20 ./coawstM > wrf_run1.out 
./coawstM: symbol lookup error: ./coawstM: undefined symbol: __libm_expf_table_64
./coawstM: symbol lookup error: ./coawstM: undefined symbol: __libm_expf_table_64`
Please help me address this issue!

**Comment by jcwarner-usgs** [comment]
not sure.
does this help:
https://community.intel.com/t5/Intel-Fortran-Compiler/undefined-symbol-libm-feature-flag/td-p/1076401

??-j



John C. Warner, Ph.D.
U.S. Geological Survey
384 Woods Hole Road
Woods Hole, MA 02543
508-457-2237<tel:508-457-2237> ph. 508-457-2310<tel:508-457-2310> fax
jcwarner@usgs.gov<mailto:jcwarner@usgs.gov>

https://www.usgs.gov/staff-profiles/john-warner


________________________________
